### ISSUE TITLE
Put a SpriteSheet Into ResourceManager

### ISSUE THREAD

**Issue by JaredPoetter** [4950/DirtyGame#10]
We need to put a SpriteSheet into ResourceManager so that the user can access SpriteSheets instead of Texture2D. 

Before:

```
sprite.SpriteSheet = new SpriteSheet(resourceMgr.GetResource<Texture2D>("playerSheet"), "Content\\PlayerAnimation.xml");
```

After:

```
sprite.SpriteSheet = resourceMgr.GetResource<SpriteSheet>("playerSheet");
```

**Comment by sturmE** [comment]
I think its better to close the issue after the pull request has been merge. Or..did you do this already and its in develop.

**Comment by JaredPoetter** [comment]
I was going to put it in and it looks like someone already changed the code to use it. Because your code is flexible enough to just pass in any string into the content loader and it returns it.
