### ISSUE TITLE
Implement MoveSpeedUp Modifier

### ISSUE THREAD

**Issue by Quillwerth** [4950/DirtyGame#103]
DEPENDS ON #99.

Implement MoveSpeedUp (15%+ to moveSpeed). Applicable to all enemies, except Flametower.

Every constant in this ticket should be easily modifiable, so that during play testing these can change if necessary.

**Comment by bkern24** [comment]
Do we want this still? Not hard to implement

**Comment by dawl** [comment]
Not Implementing
