### ISSUE TITLE
Create a Gameplay Data Capture System (GDCS).

### ISSUE THREAD

**Issue by FourierTransformer** [4950/DirtyGame#104]
At the end of each round, the GDCS needs to capture certain statistics of the round just played.

The statistics are:
Amount of hits on player/total enemy attack (Note: #97)
DamageDealt/Total Enemy Health
Total Kills / Total Enemies
FinalHealth
Roundtime
Player Accuracy (amount of hits a player lands / total number of attacks done)
Graze/total number of enemy attacks #107 

This data will eventually be sent to a server.

EDIT:
This issue is the same as the logging issue, just with a little more definition of what we want to collect. #37

**Comment by AOEChamp** [comment]
I'm thinking they way this will work is: The game will run SQLite internally to log events.

When we need to send data to the server, we can either:
A. Send the sqlite file
B. Send JSON

And then our webserver will read the data and store it in a MySQL database

**Comment by Quillwerth** [comment]
Taking this off of high priority. Yes, it's important, but before we worry about this, the game has to be done.

**Comment by AOEChamp** [comment]
The capture system is done. Just need to capture the relevant data now

**Comment by JaredPoetter** [comment]
Adeeb please ASSIGN yourself and CLOSE the tickets that you complete. So we do not waste time developing something more than once.

**Comment by AOEChamp** [comment]
I didn't want to close it until we were sure everything necessary was being
captured
