### ISSUE TITLE
Implement FireTrail Modifier

### ISSUE THREAD

**Issue by Quillwerth** [4950/DirtyGame#106]
DEPENDS ON #99.

Implement FireTrail Modifier (gives Fire Trail to an enemy permanently, see #97) Applicable to all enemies except Flametower.

Every constant in this ticket should be easily modifiable, so that during play testing these can change if necessary.

**Comment by JaredPoetter** [comment]
I think that this is not going to be one of the high priority items this time around. I think that we should get the modifier system working with move speed up and damage up first. Just want to make sure whoever is working on this is not going to spin their wheels on something.

**Comment by JaredPoetter** [comment]
Not doing
