### ISSUE TITLE
Implement "Graze"

### ISSUE THREAD

**Issue by Quillwerth** [4950/DirtyGame#107]
Each attack will have a "grazing box": a slightly larger (10px buffer) hitbox around the original hitbox. If an attack hits the player with the graze box, but not the inner hitbox, the attack does not damage the player, and the player is awarded a "grazing bonus". See #104.

**Comment by bkern24** [comment]
I'll work on this.

**Comment by bkern24** [comment]
We don't want this anymore correct? as it leads to a time based calculation????????????????????/

**Comment by FourierTransformer** [comment]
ah, you're right. This would factor in to time. So yeah, not truly needed.
