### ISSUE TITLE
Obtain a server

### ISSUE THREAD

**Issue by FourierTransformer** [4950/DirtyGame#108]
We need a server. Preferably one with some sort of SQL-like database and (preferably) the ability to scale under load. Might need to do some research on this a bit.

If need be, we could get [un]managed VPS from someplace like linode and setup our own system.

Look into: Rackspace, Amazon, and Cloud web server.

**Comment by FourierTransformer** [comment]
@baylorw I think @AOEChamp was saying we can get ahold of an Azure server if we sign up for something.

**Comment by AOEChamp** [comment]
http://www.windowsazurepass.com/azureu

Easy sign up page there. Not sure if you've filled it out yet Baylor. If not, I can fill it out with your infos. John told us to use that page.

Also, Amazon:
http://aws.amazon.com/grants/

**Comment by JaredPoetter** [comment]
Conrad, I can help with getting the server if you want me to look into it.

**Comment by dawl** [comment]
@baylorw if you could fill out the form at http://www.windowsazurepass.com/azureu that would be great.  Getting an azure server up and running would give Adeeb and Eric something to test their networking with.

**Comment by JaredPoetter** [comment]
@AOEChamp @dawl Adeeb could you let Conrad or myself know if you do not get a server from that form because we can email Microsoft about the server and figure out what we need to do to get the server. Thanks.

**Comment by AOEChamp** [comment]
Have server, need meeting
