### ISSUE TITLE
Server concept of Scenario

### ISSUE THREAD

**Issue by FourierTransformer** [4950/DirtyGame#109]
A scenario is the collection of enemies that a player will face in a round. The things a "Scenario" object on the server must keep track of is:
- this list of enemies, and their modifiers
- the difficulty of a scenario #110
- the captured data from each run of this scenario #104. This data should be used to calculate the inverse of the PlayerScore multiplier #111, and then sorted by this value.

**Comment by JaredPoetter** [comment]
Start working one loading the scenarios from XML for each of the maps.

**Comment by JaredPoetter** [comment]
Done with loading the scenario XML.
Need to put in the Player Spawn point in the scenario.

**Comment by JaredPoetter** [comment]
Removing myself from this ticket because I am working on loading the XML for the scenario which in the ticket #132.

**Comment by AOEChamp** [comment]
No longer relevant
