### ISSUE TITLE
Determining scenario difficulty

### ISSUE THREAD

**Issue by FourierTransformer** [4950/DirtyGame#110]
Scenario difficulty is determined by data captured from play-throughs of the scenario ( #104 ). 

We add the inverse of the player skill multiplier ( #111 ) to the scenario's list of plays after playthrough ( #109 ). 

This list should be sorted, and we take the median inverse from the list and apply it to the scenario difficulty (SD).

SDnew = SDold ( medianInverse )

This should be done after everytime playthrough data has come back.

**Comment by AOEChamp** [comment]
ELO for days
