### ISSUE TITLE
Calculate PlayerScore

### ISSUE THREAD

**Issue by Quillwerth** [4950/DirtyGame#111]
PlayerScore (PS) is a calculation that serves as a proxy for the player's ability at playing the game.

Let H be HitRate, D be DamageDealt, K be Kills, T be Total Health (See #104 ).

PSnew = ceil(PSold( max(3(1-H), .01) + 2D + 2K + 3T / (3(1-Hb) + 2Db + 2Kb + 3Tb) ))

max and ceil are used to avoid having a numerator equal to 0 or Player Score going down to 0.
    Hb, Db, Kb, and Tb are the "ideal" round values:
        Hb's value is not really known. We set it to .25
        Db = Kb = 1
        Tb -> 0 (so we set it to 0)

**Comment by JaredPoetter** [comment]
Hit Rate: (Number of Hits on Monsters)/(Total Number of Attacks)
Damage Dealt: 1 -[ (Sum of the Remaining Monsters Health)/(Sum of the Maximum Monsters Health)]
Kill Rate: (Number of Monster Kills)/(Number of Spawned Monsters)
Health Remaining: (Player Health) / 100

Things that we have to record to get the player score:
- Number of Hits on Monsters
- Total Number of Attacks
- Sum of the Remaining Monsters Health
- Sum of the Maximum Monsters Health
- Number of Monster Kills
- Number of Spawned Monsters
- Player Health

**Comment by AOEChamp** [comment]
Temporary SQL Magix:

DECLARE @Session INT;
SET @Session = 31;
DECLARE @HitRate FLOAT;
DECLARE @KillRate FLOAT;
DECLARE @RoundHealth FLOAT;
DECLARE @HealthRemaining FLOAT;
SET @HitRate = CAST((SELECT COUNT(_) FROM GameEventModels WHERE (SessionId = @Session AND Type = 'PlayerWeaponFirstHit')) AS FLOAT) / (SELECT COUNT(_) FROM GameEventModels WHERE (SessionId = @Session AND Type = 'PlayerWeaponFired'));
SET @KillRate = CAST((SELECT COUNT(_) FROM GameEventModels WHERE (SessionId = @Session AND Type = 'MonsterKilled')) AS FLOAT) / (SELECT COUNT(_) FROM GameEventModels WHERE (SessionId = @Session AND Type = 'MonsterSpawned'));
SELECT @RoundHealth = Data FROM GameEventModels WHERE (SessionId = @Session AND Type = 'RoundHealth')
SET @HealthRemaining = @RoundHealth / 100

SELECt @HealthRemaining;

**Comment by AOEChamp** [comment]
/_create function dbo.InlineMaxF(@val1 float, @val2 float) returns float
AS
begin
  if @val1 > @val2
    return @val1
  return isnull(@val2,@val1)
end_/
GO

DECLARE @Session INT;
SET @Session = 34;
DECLARE @HitRate FLOAT;
DECLARE @KillRate FLOAT;
DECLARE @RoundHealth FLOAT;
DECLARE @HealthRemaining FLOAT;
SET @HitRate = CAST((SELECT COUNT(_) FROM GameEventModels WHERE (SessionId = @Session AND Type = 'PlayerWeaponFirstHit')) AS FLOAT) / (SELECT COUNT(_) FROM GameEventModels WHERE (SessionId = @Session AND Type = 'PlayerWeaponFired'));
SET @KillRate = CAST((SELECT COUNT(_) FROM GameEventModels WHERE (SessionId = @Session AND Type = 'MonsterKilled')) AS FLOAT) / (SELECT COUNT(_) FROM GameEventModels WHERE (SessionId = @Session AND Type = 'MonsterSpawned'));
SELECT @RoundHealth = Data FROM GameEventModels WHERE (SessionId = @Session AND Type = 'RoundHealth')
SET @HealthRemaining = @RoundHealth / 100

DECLARE @TotalHealth FLOAT;
DECLARE @Monster VARCHAR(50);
DECLARE db_cursor CURSOR FOR SELECT Data FROM GameEventModels WHERE (SessionId = @Session AND Type = 'MonsterSpawned');

SET @TotalHealth = 0;
OPEN db_cursor   

FETCH NEXT FROM db_cursor INTO @Monster

WHILE @@FETCH_STATUS = 0  
BEGIN   

```
SET @TotalHealth = @TotalHealth + CASE @Monster 
    WHEN 'MeleeMonster' THEN 240
    WHEN 'SuicideBomber' THEN 1
    WHEN 'LandmineDropper' THEN 120
    WHEN 'RangedMonster' THEN 120
    WHEN 'Grenadier' THEN 100
    WHEN 'Flametower' THEN 100
    WHEN 'SnipMonster' THEN 120
    WHEN 'WallHugger' THEN 25
    ELSE 0
END;

FETCH NEXT FROM db_cursor INTO @Monster 
```

END

DECLARE @TotalDamage FLOAT;
DECLARE @CurDmg FLOAT;
DECLARE db_cursor2 CURSOR FOR SELECT Data FROM GameEventModels WHERE (SessionId = @Session AND Type = 'MonsterDamageTaken');

SET @TotalDamage = 0;
OPEN db_cursor2  

FETCH NEXT FROM db_cursor2 INTO @CurDmg
WHILE @@FETCH_STATUS = 0  
BEGIN  
    SET @TotalDamage = @TotalDamage + @CurDmg;
    FETCH NEXT FROM db_cursor2 INTO @CurDmg
END

DECLARE @DamageDealt FLOAT;
SET @DamageDealt = @TotalDamage / @TotalHealth;

/_SET @HitRate = 0;
SET @DamageDealt = 0;
SET @KillRate = 0;
SET @HealthRemaining = 0;_/

DECLARE @PlayerScore FLOAT;
SET @PlayerScore = (dbo.InlineMaxF(3 \* (@HitRate), .01) + 2 \* @DamageDealt + 2 \* @KillRate + 4 \* @HealthRemaining) / (3 \* (1) + 2 \* 1 + 2 \* 1 + 4 \* 0);

PRINT 'Hit Rate: ' + CAST(@HitRate AS VARCHAR)
PRINT 'Kill Rate: ' + CAST(@KillRate AS VARCHAR)
PRINT 'Health Remaining: ' + CAST(@HealthRemaining AS VARCHAR)
PRINT 'DamageDealt: ' + CAST(@DamageDealt AS VARCHAR)
PRINT 'Player Score: ' + CAST(@PlayerScore AS VARCHAR)
