### ISSUE TITLE
Networking infrastructure (be able to send messages b/n client and server)

### ISSUE THREAD

**Issue by FourierTransformer** [4950/DirtyGame#112]
Be able to receive data collected by the GDCS ( #104 ) on server.

Client needs to be able to receive scenario data ( #109 ).

Must be concurrent with multiple clients.

**Comment by eric1989** [comment]
I can look at this issue.

**Comment by Quillwerth** [comment]
I know this is where your interests lie, Eric, but we could really use
focus on the high-priority tasks. You can assign this to yourself, but
please take a look at the other tasks and see if you can pick up a few of
those first.

Ping me if you want rationale behind my request.

**Comment by eric1989** [comment]
yeah. Sounds good.

**Comment by AOEChamp** [comment]
ODATA OP
