### ISSUE TITLE
Identify users on server

### ISSUE THREAD

**Issue by Quillwerth** [4950/DirtyGame#116]
Decide if people playing the game will have an identity on the server or not.

@AOEChamp: Weigh in on the technical challenges / requirements for (registered users && unregistered users && anonymous users)

**Comment by Quillwerth** [comment]
Whoops.

**Comment by AOEChamp** [comment]
So.

Registered Users: Requires users to create an account to play. Can be very simple. Allows us to track all sessions for a user, and customize the game to that user. Also allows us to collect optional metrics like Age and Gender. 

Unregistered Users: We don't have a formal registration process, but try to link game sessions together with a virtual user. We can determine users by a unique id, consisting of things like ip address, mac address, hard drive ids, etc. This allows us to collect information per user to some degree(or at least per computer).

Anonymous Users: We don't distinguish between users at all. We only have lots and lots of session data. Minimal customization per user will be possible.

**Comment by lingqingmeng** [comment]
Do we actually need to bother with the third option of anonymous users? I would vote on only have Registered and Unregistered type of users. What are other people's thoughts on this?

**Comment by AOEChamp** [comment]
The point is to pick one option.
