### ISSUE TITLE
Global Leaderboard

### ISSUE THREAD

**Issue by Quillwerth** [4950/DirtyGame#117]
Hash out details w/ design team for global leaderboard on PlayerScores.

**Comment by lingqingmeng** [comment]
I shall work on this today
Edit: 2:02 PM - Class UML rough draft completed. Would need Azure server Class UML diagrams to implement further. For now have local and global leaderboard classes and their core methods.

**Comment by JaredPoetter** [comment]
We do not need to focus on the leaderboard until we have a working game that can use the leaderboard. I would work on some of the other High Priority issues before you go to much further.

**Comment by lingqingmeng** [comment]
Got it. Will delay this until further notice.

**Comment by AOEChamp** [comment]
Replaced by #295
