### ISSUE TITLE
Implement RangeUp Modifier

### ISSUE THREAD

**Issue by Quillwerth** [4950/DirtyGame#118]
DEPENDS ON #99.

Implement RangeUp (+10% range on FiringDistance). Applicable to Grenadier, FlameTower.

Every constant in this ticket should be easily modifiable, so that during play testing these can change if necessary.

**Comment by JaredPoetter** [comment]
This means that we are going to need to have a normal range to each of the range weapons so that we can have a range up.

**Comment by JaredPoetter** [comment]
Not doing
