### ISSUE TITLE
Server Design

### ISSUE THREAD

**Issue by FourierTransformer** [4950/DirtyGame#120]
Design team needs to work out some of the details on how the server should be implemented.

**Comment by AOEChamp** [comment]
I call being Server Master :P I think server design will largely be influence by platform. If we are going with a custom linode or something, then we will have to use a scripting language(PHP???). If Azure, then we're using C#/ASP.net. If Amazon, then whatever Amazon uses...

**Comment by Quillwerth** [comment]
Please, not PHP. C# would be preferable as everyone (should!!!!) know it.

**Comment by FourierTransformer** [comment]
I'm pretty sure if you have [un]managed vps on linode, you can run whatever web apps you want as long as you're within system resources. AKA not limited to PHP.

A "shared" hosting plan would end up with a PHP only system - and likely fail pretty catastrophically as resources likely wouldn't be enough for > 500-1000 people. (or at least that's when non-cached Wordpress fails).

**Comment by AOEChamp** [comment]
Yea, Azure with C# seems like the best option.

**Comment by lingqingmeng** [comment]
Is the game going to require a persistent connection or is available to play offline too?

**Comment by bkern24** [comment]
I would assume persistent connection for data collection purposes

**Comment by Quillwerth** [comment]
I know it's bad game design, but we're gonna need a persistent connection.
If this was primarily a game project, we'd build a system to allow offline.
But it's not, it's primarily an AI project.

**Comment by eric1989** [comment]
I think we need first to identify what kind of functions a server needs to obtain (specifically).
