### ISSUE TITLE
Update Wiki with "Dirty 2.0" additions

### ISSUE THREAD

**Issue by FourierTransformer** [4950/DirtyGame#121]
you know, from the txt document.

**Comment by FourierTransformer** [comment]
Dirty 2.0 Game Mechanics Added!

https://github.com/4950/ShittyPrototype/wiki/Game-Mechanics

**Comment by JaredPoetter** [comment]
Thanks for posting this, it should help the team know what we all are trying to develop in the game. I also put a link to the page on the sidebar of the Wiki page, for quick access to the page.

**Comment by FourierTransformer** [comment]
Yeah, I was wondering how to do that and was going to ask you a little
later on today. Anyway, there should be a few more updates coming from the
design team.

**Comment by FourierTransformer** [comment]
Done a while ago.
