### ISSUE TITLE
A* need to be modified in order to cooperate  with the wall.

### ISSUE THREAD

**Issue by eric1989** [4950/DirtyGame#124]
I just find that there is a wall between you and an enemy. The enemy cannot find a path to walk around the wall to you. They just face to you and do some thing. This needs to be modified.

**Comment by JaredPoetter** [comment]
My guess is that you will need to do something with the definition of the map so you can have the AI know when it is near a wall.

**Comment by AOEChamp** [comment]
There is an array of tiles in the map class. Each tile has a passability
bool which will tell you whether it is a wall or not

**Comment by bkern24** [comment]
Ray casting is also available in the Physics class, so see Github wiki on how to use it.

**Comment by eric1989** [comment]
@AOEChamp I think you are right. We just set a boolean which will tell you whether it is a wall or not.
If it is a wall, then you cannot pass it, my guess is that we also need to modify the right rate for the wall in the A*, in order to let AI know this path is not shortest path.

**Comment by eric1989** [comment]
I have not see the code yet. But, my guess for the map is equal rights. So, we need to change rights for the wall.

**Comment by bkern24** [comment]
If i am understanding this correctly. The wall tiles have already been setup as an entity correct @dawl ??? Then you use ray casting to grab all entities in your path and then check what entities they are. i.e if the entity has a wallComponent (Or whatever its called, asked Conrad) then that would mean a wall is in your way. 

You should not have to worry about the actual tiles of the map as that is handled elsewhere. So again I say look into ray casting on the wiki.

**Comment by AOEChamp** [comment]
Think we have A\* now. Or the code for it.
