### ISSUE TITLE
Documenting/Drawing Up All Components & Systems

### ISSUE THREAD

**Issue by JaredPoetter** [4950/DirtyGame#13]
I was thinking that it might be a good idea to draw/document all of the components in some sort of tool like Visio or Google Draw. I am noticing that we are going to have a lot of components and systems in the near future and it would make it easier for myself and the rest of the group to make a visualization to use as a reference. It would be nice to use a tool that allows all of us to modify it without needing to send it around the group in an email. 

Here is a list of tools that I found on a stackoverflow post.
http://stackoverflow.com/questions/6877121/is-there-a-free-browser-based-uml-modelling-tool

If any of you have a good idea for a tool that we all can get a hold of that is free, post it in a comment on this issue.

**Comment by JaredPoetter** [comment]
Looking at all of them it seems GenMyModel might be a good one but I am going to wait and see what you guys think before we start creating it.

EDIT: Sorry I don't think that GenMyModel has collaboration implemented in their beta version of the software. So this one is off the table I think.

**Comment by mplewis** [comment]
I personally prefer Omnigraffle and can acquire copies for everyone.
Unfortunately, it's only an OS X app.

**Comment by sturmE** [comment]
Ive got it started on the wiki
https://github.com/4950/ShittyPrototype/wiki.

As you can see we have all the components in the sidebar. Peolple just need to add the components they make.
