### ISSUE TITLE
SoundEffects for weapons & Background Music

### ISSUE THREAD

**Issue by JaredPoetter** [4950/DirtyGame#131]
SoundEffects for the weapons, Background Music and a Sound System to play the sounds.

**Comment by FourierTransformer** [comment]
@AOEChamp and I took care of this. Should be in dev now.

**Comment by FourierTransformer** [comment]
Just leaving this open, as we may have to secure more sound effects for different enemies in the future.

Once I get the chance to play with it, I'll see what's going on with it.
