### ISSUE TITLE
Fix Animation(s)

### ISSUE THREAD

**Issue by FourierTransformer** [4950/DirtyGame#145]
Fix the sword animation and the speed of the bow attack(s) and any sprite sheets as necessary

**Comment by FourierTransformer** [comment]
Quick Update: Pretty much done. Just need to hack together a new player sprite with sword and bow animations. A little Photoshop and this should be done.

**Comment by FourierTransformer** [comment]
Done. New player animation should be in with the latest merge.

**Comment by lingqingmeng** [comment]
Reopening for long sword over dagger

**Comment by lingqingmeng** [comment]
https://github.com/4950/DirtyGame/commit/1805cc7a99277581d033ab53b78173f80057ffd8

Closed as of this
