### ISSUE TITLE
Bug with Changing the Location of the Player

### ISSUE THREAD

**Issue by JaredPoetter** [4950/DirtyGame#146]
@AOEChamp @bkern24 I was wondering if either of you or anyone else has an idea of what is going wrong. I am not able to change the location of the player after the player entity is created in the entity factory. Here is basically what my code is trying to do in just a couple of lines. Just put them in after the adding of the player weapons to the player and see if you can find anything wrong with what I am doing.

```
e.Refresh();
player.GetComponent<InventoryComponent>().addWeapon(e, player);

//New Code
player.GetComponent<SpatialComponent>().Position = new Vector2(300.0f, 300.0f);
player.Refresh();
//

//start sound
SoundSystem.Instance.SetGame(this);
SoundSystem.Instance.MaxVolume = .20f;
```

I am also thinking that there might have to do with the Physics System maybe because when I go into the entity factory and change the spatial component values it works fine to move the player.

Please let me know as soon as possible what you might think is the problem with my code.

**Comment by JaredPoetter** [comment]
Update: I might have found a problem with the Entity/Component/System framework or just something to look out for. If I remove the player.Refresh(); in the setup of the player and then do it after I change the Spatial it works. So you might not be able to call the refresh function more than once per pass through the game's systems.

Let me know if you run or ran into this bug anywhere else. Maybe Eugene, @sturmE, would have any idea on what is going on here because it is most likely a bug.

**Comment by sturmE** [comment]
ill take a look at this tonight.

On Tue, Feb 11, 2014 at 3:22 PM, Jared Poetter notifications@github.comwrote:

> Update: I might have found a problem with the Entity/Component/System
> framework or just something to look out for. If I remove the
> player.Refresh(); in the setup of the player and then do it after I change
> the Spatial it works. So you might not be able to call the refresh function
> more than once per pass through the game's systems.
> 
> Let me know if you run or ran into this bug anywhere else. Maybe Eugene,
> @sturmE https://github.com/sturmE, would have any idea on what is going
> on here because it is most likely a bug.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/4950/DirtyGame/issues/146#issuecomment-34808492
> .

## 

Eugene Sturm

**Comment by JaredPoetter** [comment]
@sturmE Thanks I am assuming that this is not the desired outcome. But it is at least easily repeatable bug. I hate the ones that you are not able to repeat every time.

**Comment by sturmE** [comment]
I saw someone added a flag for e.isDataEntity in the refresh call. Verify that isnt the issue before I dig deeper since I dont know the purpose of that haha.

**Comment by JaredPoetter** [comment]
Can you see who added that line?

**Comment by sturmE** [comment]
I'm in my phone. The refresh call is in World class

**Comment by JaredPoetter** [comment]
I thought that you were on the GitHub app I will see who added the line if you didn't.

**Comment by sturmE** [comment]
Thats too much effort

**Comment by JaredPoetter** [comment]
Well it looks like it is @AOEChamp code change so do you think that is the change the broke the code? I can ask him about more tomorrow but he will probably respond to this issue because he has gotten all of these comment as emails.

**Comment by sturmE** [comment]
I'm not saying it broke it. I'm just saying that it is something that would
prevent a refresh and I don't know what that flag is used for.

**Comment by sturmE** [comment]
Also, your example code looks like you are calling Refresh() after updating a component that is already a part of the entity. Refresh() is meant to be called after you add new components, not after you alter components.

**Comment by AOEChamp** [comment]
Data entities are not refreshed, yes. But the player entity is not a data entity. The reason position does not change after a refresh is because of the physics system. From then on, the spatial position is set by physics.

**Comment by JaredPoetter** [comment]
Yea I guess I did not think about going back to this ticket after I
 figured out that the Physics system is the problem.

Thanks
Jared Poetter

**Comment by JaredPoetter** [comment]
I am going to close this because I am thinking that it might not be a bug but just a thing that is going to be there when we are using the Physics system.
