### ISSUE TITLE
"Dud" Landmines

### ISSUE THREAD

**Issue by Quillwerth** [4950/DirtyGame#155]
MineLayers are connected to the mines they lay, insofar as when the MineLayer dies, their mines become "duds": they do no damage upon touching them. This shouldn't be the case.

**Comment by dawl** [comment]
Done

**Comment by lingqingmeng** [comment]
Reopening for despawn part

**Comment by lingqingmeng** [comment]
Closed as of this commit.

Mines do damage if its owner dies. The mine stays there until..
Mines get cleared when level is over. 

https://github.com/4950/DirtyGame/commit/1805cc7a99277581d033ab53b78173f80057ffd8
