### ISSUE TITLE
Mobs touching the outer border of the map lose their healthbar

### ISSUE THREAD

**Issue by Quillwerth** [4950/DirtyGame#168]
this includes the player.

Note that this isn't when you're touching the outer _wall_ , it occurs only when there is no wall to touch. So if you put walls around the border of all the maps... **shrug** okay

**Comment by AOEChamp** [comment]
I vote wallz

**Comment by JaredPoetter** [comment]
I vote for walls too because that will also give the maps a more natural
look compared to the abrupt transition from the map to the end of the
screen.
