### ISSUE TITLE
Sprite animation from multiple parts

### ISSUE THREAD

**Issue by JaredPoetter** [4950/DirtyGame#17]
Advance the sprite animations by creating each sprite from multiple sections. So the head would be animated separately from the body. This would allow us to create any type of monster or player if we had enough sprite sheets to justify implementing this feature.

"You can even go further and compose a "sprite" of multiple sprites (ex. head sprite, body sprite, legs sprite). Then you can animate each body part." - Eugene

**Comment by sturmE** [comment]
I think thats the first time I've ever been quoted.

**Comment by sturmE** [comment]
You could probably put a label on these for "Animation Improvements"

**Comment by Quillwerth** [comment]
@coala2000 Still working on this? Close it if you aren't.

**Comment by JaredPoetter** [comment]
This was an idea that Eugene had for me to work on but it is probably not going to happen within the semester.

**Comment by sturmE** [comment]
Crushing my dreams.
