### ISSUE TITLE
At round end, a menu with a button to continue on to the next round

### ISSUE THREAD

**Issue by Quillwerth** [4950/DirtyGame#170]
All in the title. Also, congratulate them on surviving yet another round. Yaaaay.

**Comment by JaredPoetter** [comment]
Maybe you can have a running counter on how many scenarios they have
completed in that sitting or all together. Also you can show some sort of
score for the scenario.

**Comment by AOEChamp** [comment]
I think some text saying round whatever plus a 5 or 10 second countdown would be better. NO BREAKS

**Comment by JaredPoetter** [comment]
Well lets code it one way but make it possible to change it to the other
way either by a setting or a somewhat quick code change. Because we might
find out that the people want a break or they do not.

**Comment by AOEChamp** [comment]
Think Arcade games. You do or you die :P

**Comment by lingqingmeng** [comment]
Food for thought: If they have a pause button, they won't care. They'll
just pause when the round starts.

**Comment by JaredPoetter** [comment]
Then we should have a dedicated ‘pause’ button and have it shown somewhere on the screen or before the scenario starts so they know how to. If we do not have it shown at that time they might frantically try to find some way to pause and then they end up getting killed and that will hurt their player score some.

**Comment by AOEChamp** [comment]
I think you guys will like it :P
