### ISSUE TITLE
Finite vs Looping Animation

### ISSUE THREAD

**Issue by sturmE** [4950/DirtyGame#18]
Add in someway to specify whether an animation should loop indefinitely or just play through once.

**Comment by Quillwerth** [comment]
@coala2000 Did we finish this?

**Comment by JaredPoetter** [comment]
I think that I have this working but I have not tested on more than my sprite sheet for the sword animation. So once myself or another developer starts playing with more than the animations that I made last semester this can be closed.

**Comment by JaredPoetter** [comment]
I think that this is working but I might not be surprised if there would be a bug found in it when people start using it more.
