### ISSUE TITLE
Tile collision seems to be 1 tile off?

### ISSUE THREAD

**Issue by FourierTransformer** [4950/DirtyGame#186]
Tile collision seems to be 1 tile lower in the "y" direction on all of the maps. This seems to be a recent development. (and causes some serious issues with the new Cave)

@AOEChamp @dawl you guys have done some mapping stuffs, any idea what's up?

**Comment by AOEChamp** [comment]
It's just the bounding box on the player. Enable physics debug to see.

**Comment by FourierTransformer** [comment]
wait, are we really using physics to determine tile collisions? oh boy...

**Comment by AOEChamp** [comment]
Physics for days
