### ISSUE TITLE
More information in defining animation

### ISSUE THREAD

**Issue by JaredPoetter** [4950/DirtyGame#19]
Being able to specify more information in the XML file to create a animation that has more options like:
- Put the SpriteSheet texture file location into the XML as an attribute.
- Variation in time for each frame of the sprite to render for.
- Ability to specify the rectangle of each frame on a single sprite sheet of an animation.
- Multiple ways to define an animation on a sprite sheet. Each frame separate or simpler method.

Post more if there are more things that you think would be nice when creating an animation. They can be improvements to make it easier or so you can change the animations without needing recompile the program.

**Comment by Quillwerth** [comment]
@coala2000 is this still desired or in development? Keep in mind we have more pressing stuff (at least, in my opinion). Close it if we don't want it.

**Comment by JaredPoetter** [comment]
I actually finished all but variation in the amount of time each frame is. I am going to close it. But there might be a new ticket if people find a bug in my code because once again no one used my code beyond what I did.
