### ISSUE TITLE
Fix boundary size and location on monsters and player

### ISSUE THREAD

**Issue by JaredPoetter** [4950/DirtyGame#190]
Fix boundary size and location on monsters and player. Move it to the torso.

**Comment by AOEChamp** [comment]
We need to decide how large the boundaries should be(unless this was already talked about). Making it the size of the sprite is usually too big, but what we have right now is too small. Some playtesting may be needed to see what makes a decent hitbox, but not so large as to frustrate players.

**Comment by dawl** [comment]
Collision box is not at player/monster's feet

**Comment by bkern24** [comment]
It covers their entire body? So we just want collisions at their feet? I get why you might want that but it will make the game look weird.

**Comment by bkern24** [comment]
Nobody has said anything in week or two so..................
