### ISSUE TITLE
Sword weapon attack should match the longsword animation

### ISSUE THREAD

**Issue by lingqingmeng** [4950/DirtyGame#196]
Sword animation is implemented right now with a big swinging sword that goes with the player. 

Right now we need the sword hitbox to change from a square instantly appearing (and staying static)

Perhaps we need to make the player speed zero during the duration of the sword attack.

Also, sword's hitbox should radially rotate to match the sprite images. It could be implemented similar to a 180 degree faster flame tower. Essentially the idea is to have a rotating hitbox.

@AOEChamp 
If could work on this (is pretty challenging) that would be great. Or if there is any solution you would recommend for this please let us now.

**Comment by bkern24** [comment]
Changing the Collision box is possible through setVertices but I think it would be much easier to set a default collision size, and then just rotate it? If that sounds okay then I'll take this one

Also note that I forgot to return false if its a melee collision so the physics box for the sword "moves"....

**Comment by bkern24** [comment]
Okay see Brandon/LongSwordPhysics....... Its a much better implementation. I'm not saying its great but its better. We still have to change the timing of the sword entity

**Comment by lingqingmeng** [comment]
Just merged my fixes with the disappearing player when shooting bug. Also made a couple of aesthetic improvements. Ready for your changes now too!

**Comment by bkern24** [comment]
Pretty sure this is done as well
