### ISSUE TITLE
When firing Range weapon Player turns invisible

### ISSUE THREAD

**Issue by bkern24** [4950/DirtyGame#197]
Unless its a new ability???????????????????

**Comment by AOEChamp** [comment]
Tried looking into it, very weird. The animation is set correctly and exists. Frames are also set. Yet no show.

**Comment by lingqingmeng** [comment]
Reason was because I edited the wrong section (Shoot instead of Bigslash) when doing my sword animations. My bad haha >.>. Fixed as of:

commit 9f0953df97014bc68db349411e015119c44198bd
