### ISSUE TITLE
Longsword animation problem on map edge

### ISSUE THREAD

**Issue by lingqingmeng** [4950/DirtyGame#201]
Longsword animation has a bug if player hugs a wall that is the edge of the map.

The animation appears 4 spots left of the player if he's on the right wall, and the player disappears until the attack animation is over.
Something similar happens on the bottom wall. 

 A quick fix would be to make a border 256 pixels between the edge of the map and the player. I.E. add 4 layers of trees around each edge. 

A complete fix I'm not sure on how to best go about this. Because the longsword sprite animation has to be size 192x256, instead of 64 by 64. Otherwise, the sword is too long, and we'll have overlapping sprites if we make them any smaller. 

@AOEChamp @bkern24 @coala2000  Any suggestions on how to fix this?

**Comment by lingqingmeng** [comment]
Some updates
progressbar = healthbar I found out after a long search 

Only the progress bar seems to be glitching, not the player animation anymore.

Player stands next to wall, swings sword
       -Player animation working as intended. Health bar will fly 4 spaces to the left, if the player is on 
        a rightside wall. It will fly 3 spaces to the top if player is on a bottom wall.
       -If a player issues a move command right after the attack animation. The attack animation        disappears and the health bar goes back to the player.

So I think I know whats going on
    -The map boundaries system that checks if a projectile/player is going to a boundary changes the position of the player.

if (pos.X > renderer.ActiveMap.getPixelWidth() - 
     e.GetComponent<SpriteComponent>().SrcRect.Width){
                    pos.X = renderer.ActiveMap.getPixelWidth() - 
                    e.GetComponent<SpriteComponent>              ().SrcRect.Width;
....}

-The Process Entities function for that system seems to be detecting every single entity.
-The progress bar's position is being erroneously set to a scale (192x256 instead of 64x64) that makes it so it feels the need to push the healthbar back by 192 pixels whenever a longsword swing is made. 

Would like insight on this, thanks!

**Comment by AOEChamp** [comment]
Well, I checked the system and it's not the progressbar code that is glitching. Spacial positon is being changed after the sword swing. Did a test standing against a wall.

Just standing: (690, 894)
After swinging sword: (690, 768)

So something is changing the player's location when the sword swings...

**Comment by AOEChamp** [comment]
Found the problem. MapBoundarySystem was setting player position and was old broken code that we aren't using. I'll commit a fix.
