### ISSUE TITLE
Collision Box Fix for the Player

### ISSUE THREAD

**Issue by JaredPoetter** [4950/DirtyGame#207]
The player collision box so that it is not at the head but is moved to the middle of their body.

**Comment by bkern24** [comment]
Are we keeping the box the same size? Or are we modifying the size based on play testing?

**Comment by bkern24** [comment]
Don't worry guys, I got this (Fist bump to chest)

**Comment by bkern24** [comment]
Can somebody in design check my branch Brandon/MoveCollisionBox
The way I was wanting to offset the collision boxes had caused issues elsewhere so I just made the collision boxes "less static" (I base off the sprite size and scale but I still use hard coded values). I want to know if they are decent or if you guys want better.

@fualkner @FourierTransformer @lingqingmeng

**Comment by bkern24** [comment]
Also anybody else who wants look at it can to. I want feedback.

**Comment by bkern24** [comment]
Well If nobody wants to look at it....

**Comment by JaredPoetter** [comment]
I have not had time to switch back over to the project since yesterday when I worked on the spawn points. I can take a look later on today if you want me to still. It just wont be for some time.

**Comment by bkern24** [comment]
Its all good, I'll just make a pull request plus I found a bug with the sword I fixed in this update too... Worst case we can remove or modify the boxes afterwards

**Comment by bkern24** [comment]
Basically Done now.. I saw the issue in cave..... The bridge should really be made bigger in reality
