### ISSUE TITLE
Converting MonsterSystem to a generic MovementSystem

### ISSUE THREAD

**Issue by dawl** [4950/DirtyGame#21]
I'm working on making a general movement system so we can move anything that has a movement component, not just a monster component.

**Comment by JaredPoetter** [comment]
I was just wondering what a ballpark figure when this or the input system is going to be implemented so that I am not spinning my wheels.

I think that Gary was going to be working on the input system. I will make a ticket for the InputSystem.

@gcoetz

**Comment by dawl** [comment]
I've got the system up and running on the etzel/AIImprovements branch.  Feel free to take a look at the MovementSystem.

**Comment by AOEChamp** [comment]
MonsterSystem was deprecated a while ago. Removing from source
