### ISSUE TITLE
Starting a scenario is not working like it was last week

### ISSUE THREAD

**Issue by JaredPoetter** [4950/DirtyGame#210]
I have been trying to get the new spawn points for the player and monsters but I think I found a bug that was not there last week. The player does not move to the new spawn point after each scenario is over. The player regains his health and stays in the current location. It seems to pull the spawn point for the very first scenario but none of the future ones.

I was looking through the code and noticed that the code I wrote to setup the scenarios has been modified. The commented lines were the original way I was switching to the new spawn point. If this is a design change let me know.

```
public void LoadScenario(string mapName)
        {
            //Setting up the scenario for the map
            gLogicSystem.StartPreRound();
            //Scenario playingScenario = gLogicSystem.randomScenario(mapName); //This will change to gLogicSystem.scenarioForPlayerScore(string mapName, float playerScore)
            //gLogicSystem.setupScenario(playingScenario);
            //player.Refresh();
        }
```

I looked at the blame and It says that the line of code was last changed by @AOEChamp  so I am going to assign this to you because you probably know what the issue is and maybe can give me some insight into what the problem is.

**Comment by bkern24** [comment]
I don't think it was adeeb. I believe what happened was that even though I know @lingqingmeng had fixed his branch after pushing old code back into develop, there were other issues still present in develop. It seems as if develop lost some of Adeebs code such as the better Keyboard input, and a few other things.

Not saying this isn't a bug, just saying its not adeeb's fault tis all

**Comment by JaredPoetter** [comment]
Thanks for the information. I am not saying that it was his fault I just looked at the blame and it said that it was his change. So I am just wanting to figure out what it is going on with the game.

**Comment by AOEChamp** [comment]
I changed the code so that the first round is a scenario and the next
rounds use the old sustem. This was for debug purposes, as we didn't have
scenarios using all the monsters. Also, the scenario start location has
moved, due to the "get ready" label showing first.

**Comment by bkern24** [comment]
So maybe he did break it lol but I agree for testing it sucks not having all monsters spawning

**Comment by JaredPoetter** [comment]
You could have asked me how to work with the scenarios or looked at the wiki page that I typed up. It is randomly picking a scenario for the selected map but you could just cut the other scenarios or comment them out for the map you want to test on.

**Comment by JaredPoetter** [comment]
#216
