### ISSUE TITLE
Aspects Don't Detect Subclasses

### ISSUE THREAD

**Issue by dawl** [4950/DirtyGame#22]
I am trying to implement a generic MovementSystem, and my plan was to have a parent class (MovementComponent) with several subclasses (AIMovementComponent, SpellMovementComponent, etc...).  However when an aspect contains the parent class (MovementComponent) the bit vector if the Aspect does not mach on bitVectors of entities containing the sub-classes.  I'm going to push up my changes, feel free to checkout my branch (MonsterSystemPort) and see the problem yourself.

As for solutions I think we need to change how Aspect.Contains(BitVector) works, but I am not sure how to change it.

Thoughts?

**Comment by sturmE** [comment]
Yes I saw this issue also. This isnt a quick fix. To work around this for now, just define you aspects to take the subclasses MovementComponents instead of the parent class.

**Comment by sturmE** [comment]
Sorry it took 3 days to see this. I didnt get an email. Next time, since you know this is directed towards me, just assign this issue to me or use @ symbol to reference me.
