### ISSUE TITLE
Getting people to play the game locally so we can play around with the data.

### ISSUE THREAD

**Issue by JaredPoetter** [4950/DirtyGame#230]
Saturday Session

**Comment by lingqingmeng** [comment]
I think we should meet at some central location, and split off in groups of
2, each pair would go to places like Walter, Biomed, Coffman, Coffee shops
around campus to have people play the game.

**Comment by JaredPoetter** [comment]
That is a good idea. We might run into problems with buildings being open on Saturday. Also we could probably do these play tests separately if some of us cannot make it.

I might just do a play test with a couple of my friends at home because I can do more in the time that I would be commuting to campus.

**Comment by bkern24** [comment]
I have to ask are giving gifts to people for testing? 

Also I could also get at least 10 people this weekend to test it for probably 20 min each? So if a form is ready by Saturday we could get some data. I may even get more people.. I live with 50 people so yea
