### ISSUE TITLE
Exposing the scenario that the people are currently on.

### ISSUE THREAD

**Issue by JaredPoetter** [4950/DirtyGame#234]
This would be on the GUI of the game.

**Comment by JaredPoetter** [comment]
I am thinking that we do not want to just say the scenario name because I called mine easy hard medium difficulty in the name of the scenario. So we do not want to give the player any indication that the current scenario is hard or easy.

One thing that we can do it rename all of the scenarios to just a letter or two and then display that in the upper left or right corner so the proctors of the tests can write down which scenario they are playing. Also we should figure out a way to have the map name and scenario name put into the database so we can easily figure out which sections in the data collection are the sessions we wrote about.

Let me know if this does not make sense.

**Comment by FourierTransformer** [comment]
This is legit. I beleive we are currently logging the map we are playing,
but I'm not sure about the scenario. Better ask @AoEChamp for some
clarification.

**Comment by AOEChamp** [comment]
Scenario names are not currently logged. Take a look at one of the existing log statements for an example. It should be a one-liner. I don't think we want to expose the scenario name to players though.

**Comment by JaredPoetter** [comment]
We are doing it for testing. You were not at the meeting to get all the details.
