### ISSUE TITLE
Form to fill out during Play Testing Session

### ISSUE THREAD

**Issue by JaredPoetter** [4950/DirtyGame#236]
We need a form to fill out when we are viewing the students playing the game. This will not be very long just a set of things that we want to write down during each game like the current scenario that they are playing and their reaching to different things.

**Comment by JaredPoetter** [comment]
This should be a google doc in the shared folder please so we all can have access to it if we want to do our own play testing.

**Comment by FourierTransformer** [comment]
Somethings worth thinking about for Thursday are the think-aloud logging,
and what sort of things should we get out of the player while they are
playing it. What do we want, what do we need? How can it help us tweak the
game? How does it help our metrics. How/does it affect the enemy hierarchy
and enemy synergy.

**Comment by JaredPoetter** [comment]
I got a rough form done in the google drive folder 'Play Testing'.

**Comment by FourierTransformer** [comment]
Went over it yesterday and finished it.
