### ISSUE TITLE
Game crashes on released version

### ISSUE THREAD

**Issue by JaredPoetter** [4950/DirtyGame#249]
The game will install and allow you to create an account and log in but when the game runs for a couple of seconds it will crash. It seems to do it on whatever menu you are currently in but I was not able to get any further than the map selection screen.

It seems to be running fine in visual studio for everyone. @AOEChamp do you have any idea what this could be? I am guessing that it has to do with some dependency with the server or another file because it is only on the released version.

**Comment by AOEChamp** [comment]
No idea. Would have to debug it

**Comment by JaredPoetter** [comment]
It sounds like all of the cases where it is not working are on new machines with no visual studio development environment.

**Comment by AOEChamp** [comment]
Turns out, for some reason the auto deploy decided that xml files go in a
different directory than the rest of the game.... Should be fixed now, I
uploaded the latest version.

**Comment by dawl** [comment]
I just downloaded the new version, now I get this error when I try to install.

![toweroffensev2 1](https://f.cloud.github.com/assets/3344817/2380430/94a44850-a8aa-11e3-9055-dfe3d2bac297.png)

**Comment by AOEChamp** [comment]
fraxed

**Comment by lingqingmeng** [comment]
Did play testing for a person and it crashed on the 11th round or so. At
work so I can't provide detailed log, but was wondering if anyone else was
experiencing this.

**Comment by JaredPoetter** [comment]
Are you working on the most recent version because it could be from the fact that counter roles off the end of the list of scenarios?

Also you said that you might be doing testing in an environment with a bad network connection so maybe if the connection is dropped with the server it will crash? I do not see this being an issue but it could be.
