### ISSUE TITLE
Log Displayed Score

### ISSUE THREAD

**Issue by dawl** [4950/DirtyGame#253]
The in game score needs to be logged to SQL at the end of each round.

We need to log:
- Total score
- Change in total score from the start of the round to the end of the round (Round End Score - Round Start Score)

**Comment by JaredPoetter** [comment]
This is not done.

**Comment by JaredPoetter** [comment]
This needs to be done before anymore play testing can be done.

**Comment by AOEChamp** [comment]
Done for reals now. It was only logging when the player died before :/

**Comment by AOEChamp** [comment]
Do we still need the change in score?

**Comment by JaredPoetter** [comment]
I would store the score at the end of each scenario/session we can figure out the gain by finding a difference. @FourierTransformer, let us know if that is not right.

**Comment by FourierTransformer** [comment]
Jared, you are correct!

**Comment by AOEChamp** [comment]
That's what I thought. So it should be working now.
