### ISSUE TITLE
Write "About" Page for website; post to site

### ISSUE THREAD

**Issue by Quillwerth** [4950/DirtyGame#259]
@AOEChamp to be notified upon completion, for posting.

**Comment by AOEChamp** [comment]
Also contact page

**Comment by Quillwerth** [comment]
CSCI 4950 started with a simple idea: 

"What if games fit the player, rather than players fitting into the game?"

Games should be fun. However, many games fall into one of two traps. Some games are too easy, and get boring quickly. Others are too hard, and are frustrating until you just turn them off. The narrow band between easy and hard is challenging, engaging, and where the fun lives. The challenge is finding that narrow band: It's different for everyone, and it moves as you become a better player.

Enter our team: 12 intrepid developers, designers, and managers, led by Professor Baylor Wetzel. Together, we've constructed the game you're about to play, in order to study the tricks, techniques, and data to build our dream: the game that grows with you.

Before we go, our most sincere thanks for checking out the project, and contributing your play-time. We couldn't do this without you. Don't stop being awesome.

~CSCI 4950

Team Members:
- Professor Baylor Wetzel
- Eugene Sturm
- Conrad Etzel
- Jared Poetter
- Patrick Severin
- Shakil Thakur
- Ling Qing Meng
- Adeeb Mohammed
- Brandon Kern
- Michael Duffy
- Matthew Lewis
- Ricky Thonglyvong
- (That guy with the RayBans?)

**Comment by Quillwerth** [comment]
Contact page... we can give them the class alias, but I think that might break down _our_ lines of communication. Anyone want to offer up an email address?

Maybe we could link them to here? Is there a good way for outsiders to give us feedback on GitHub?

**Comment by Quillwerth** [comment]
In any case, @AOEChamp please add the above post to the website, after acquiring that last guy's name.

**Comment by JaredPoetter** [comment]
We could make a Gmail account for the class and then let everyone know the email address password. We would also need to make a standard way to respond and filtering of the emails. I, @coala2000, can create a gmail account if you want me to do that?

**Comment by Quillwerth** [comment]
Do it. I don't know what sort of process we could need for emails... be courteous and professional, if you shouldn't be answering a question, don't answer it. Do we need more?

**Comment by Duffman9205** [comment]
That list is missing Austin (Roos?) and Gary (???)

**Comment by AOEChamp** [comment]
Gary the Snail?
