### ISSUE TITLE
Create Gmail Alias

### ISSUE THREAD

**Issue by JaredPoetter** [4950/DirtyGame#261]

**Comment by AOEChamp** [comment]
We could forward emails from an email account to the csci group. That way,
we all get emails, and any of us can reply.

**Comment by JaredPoetter** [comment]
So you think that we should still have one then?

**Comment by Quillwerth** [comment]
I want one, so we can block it if needs be (imagine if an AdBot got our internal email... :P )

**Comment by bkern24** [comment]
4950csci@gmail.com
