### ISSUE TITLE
melee monsters fix

### ISSUE THREAD

**Issue by JaredPoetter** [4950/DirtyGame#265]
melee monsters running into you hurts the player
boolean set if collided with the player, on separation the boolean gets set back
20 Damage
50 → 60 move speed
remove their sword
5 hits kill you

**Comment by bkern24** [comment]
I got this. Taking a break to eat then I will finish this so don't no one do it

**Comment by bkern24** [comment]
#278 
Had to set Damage to five in case player ran into monster it didn't just kill them instantly. Its cleaner this way

**Comment by FourierTransformer** [comment]
it seems to work pretty well. just saw it when putzing. It appears as if they are actually able to hit you now and have actually become a little more challenging.
