### ISSUE TITLE
ranged monster

### ISSUE THREAD

**Issue by JaredPoetter** [4950/DirtyGame#266]
Increase range; 400 → 450
Increase Arrow Speed;7 → 10, AND the player
8 hits to kill player
Can only shoot if in range

**Comment by JaredPoetter** [comment]
@dawl might have the only shooting in range done. But not in develop

**Comment by FourierTransformer** [comment]
"might have the only shooting in range done." << what does this mean? @dawl or @coala2000 can you clarify? I thought we did this one already?

**Comment by JaredPoetter** [comment]
This is the fact that the enemies only attack when they can hit you. @dawl I thought you did this on Thursday during the meeting? Did you forget to push it into develop?

**Comment by bkern24** [comment]
The last time i tested develop it was working.

**Comment by dawl** [comment]
I thought I pushed it, I can check.

**Comment by dawl** [comment]
Seems to be working in develop right now.
