### ISSUE TITLE
Trigger tiles

### ISSUE THREAD

**Issue by sturmE** [4950/DirtyGame#27]
We need to be able to trigger events by "stepping" on locations on the map. These triggers should be defined in the XML layout.

ex. Step on locations, 50000 monsters spawn next to you

**Comment by baylorw** [comment]
The design team needs to flesh out enough of the game design to be able to say what precisely we need triggers for.

Issues:
1. Size - Do we want tile, circular, rectangular, arbitrary convex poly or arbitrary concave poly?
2. Events - The systems i've used have onEnter, onStay and onExit. Some systems allow you to specify an event name (lets you trigger special things such as onTouchFire, onTouchElectricity, etc.)
3. Event System - We obviously need one. Owner = object or engine/manager? Arguments = (Object)sender?
4. Callback Language - Are we doing scripting? If so, need to decide whether callbacks go to script or C# (or both).
5. Persistency - We might want to make one-time-only triggers (bombs, special animations like a tower collapsing, etc.). Could have a hasTripped/enabled property or we could delete the trigger. If the latter, map load system and state manager need to track that.
6. Mounting - In many systems objects can be mounted to other objects. Triggers are often mounted to bullets or areas directly in front of a character (for detecting Near events).
7. Collision Layer Mask - In many systems, triggers and collision volumes are tagged with a property called the collision layer and a mask is kept saying which layers interact. For example, monsters might be collision layer=monster and player=player and monster collides with player but not with monster, allowing monsters to interact with the player but not other monsters. It's also one way of turning off friendly fire and letting heavy projectiles go through walls. This is done partially for functionality/game play and a lot for efficiency.

What we want from a trigger depends on what the game designers say we're going to do.

**Comment by sturmE** [comment]
+1 for all of this.

**Comment by Quillwerth** [comment]
Closed. Not needed. We've got the collision system, anyway.
