### ISSUE TITLE
Record Wins and Losses on Azure DB for each scenario

### ISSUE THREAD

**Issue by Quillwerth** [4950/DirtyGame#288]
We should record this since people said Archers were the strongest, but a scenario with 6 archers had the highest scenario score...

We need a way to detect discrepancies, and seeing global win/loss ratio data for each scenario would give us an absolute metric to compare our player score against. 

@AOEChamp

**Comment by FourierTransformer** [comment]
We record if they die. I'm not sure what's recorded if they quit. We could
extrapolate, but that seems a little gross. Perhaps always log how the
scenario ended. (Quit, died, or won)

**Comment by AOEChamp** [comment]
We record whether the round ended normally, and whether the player died. That is enough for the data we need.
