### ISSUE TITLE
Get the ~30 Scenarios implemented into Adeeb's god branch

### ISSUE THREAD

**Issue by JaredPoetter** [4950/DirtyGame#292]
~30 Scenarios are from Shak.

**Comment by FourierTransformer** [comment]
@AOEChamp we kind of need these in before we can get local testing up and running.

**Comment by AOEChamp** [comment]
Where are they?

**Comment by FourierTransformer** [comment]
I totes emailed them to you that one time. I'll ping the email

**Comment by JaredPoetter** [comment]
These should be put in for testing in the group. And while that is going on we can develop a method for the game to receive the scenarios from the server.

**Comment by JaredPoetter** [comment]
What is the progress on getting these put into the develop branch? We need these put in before we are able to do local testing within the group.

**Comment by AOEChamp** [comment]
Done
