### ISSUE TITLE
ELO K Values need to be Floats in SQL

### ISSUE THREAD

**Issue by dawl** [4950/DirtyGame#293]
The K values need to be floats instead of ints in the player score SQL code.

Player ELO and Scenario ELO need to be floats as well, we are having truncation problems.

**Comment by AOEChamp** [comment]
Githubs being poopy

**Comment by bkern24** [comment]
Your right adeeb, but I believe what's happening is you divide the float by an int, or vice versa, and so the code is then truncating the values to ints.....

**Comment by FourierTransformer** [comment]
Yup. When you do the power function, it returns either 1 or 0 resulting in
an incorrect expected score and then elo ends up being incorrect as well

**Comment by AOEChamp** [comment]
Not the power function, but it looks like SQL is poopy and doesn't follow the "do the calculations in the most complex number format supplied" rule. FLOAT all the things

**Comment by JaredPoetter** [comment]
So is this complete because if it is I can work on verifying that the calculations are done correctly?

**Comment by AOEChamp** [comment]
Soo, I'm testing with floats. And nothing changes.

**Comment by AOEChamp** [comment]
And the expected scores worked fine before.

**Comment by bkern24** [comment]
Well I don't know it worked before... But is it SQL that does weird things with regular division? I know some languages do some type of rounding or truncating when using the regular division symbol? But not really sure

**Comment by AOEChamp** [comment]
In any case, the code is int-free now. See if it works as expected

**Comment by JaredPoetter** [comment]
I can look at the values today or tomorrow to make sure they are correct. #302
