### ISSUE TITLE
Suicide Bomber 2ticks to 1tick

### ISSUE THREAD

**Issue by FourierTransformer** [4950/DirtyGame#299]
His animation still has two ticks, it should have 1. He should do 30 damage, have 60 health, and delete himself after he blows up.

**Comment by bkern24** [comment]
Can someone explain this usage of ticks? Everything else I understand. also I cannot recreate the issue of the suicide bomber damaging the player twice, can anyone else? @FourierTransformer

**Comment by Quillwerth** [comment]
Why is this even a problem? Why "should" it change? Is it actually a
balance issue, or is it simply picky? We have to direct energy carefully.

**Comment by FourierTransformer** [comment]
It's partially a balance issue (they do 31 damage to you). Partially a
visual issue (their health bar is almost all red).

From my understanding the ticks make it so the player can walk into the
explosion twice making their health go down twice from the explosion.

**Comment by bkern24** [comment]
Well I can't recreate the getting damage done twice... I tried staying in the field for the duration and tried running out of the field and then back into it... And I haven't seen double damage

**Comment by FourierTransformer** [comment]
Huh, maybe that part was fixed when we scaled his health/damage component...

**Comment by bkern24** [comment]
#309
