### ISSUE TITLE
Server Access Time

### ISSUE THREAD

**Issue by FourierTransformer** [4950/DirtyGame#301]
Either this needs to be reduced or a mini game or something that can be done to make this a hair faster. At least start a disco here so we know what's up.

**Comment by AOEChamp** [comment]
How bad is it? Not more than 1-5s for me

**Comment by FourierTransformer** [comment]
We were getting between 5-15 seconds on campus.

**Comment by AOEChamp** [comment]
Hmm. Yea, I see that now. It's already sped up a ton now that data is being sent in batches. Not sure if it will get any faster. This is why sending a single JSON packet woulda been so much better then silly RESTful services. But meh

**Comment by FourierTransformer** [comment]
Looks like this has been completed and is now in the main branch.
