### ISSUE TITLE
What to do when the internet craps out during gameplay?

### ISSUE THREAD

**Issue by FourierTransformer** [4950/DirtyGame#305]
Currently I believe we error out in both the release and debug versions.

**Comment by AOEChamp** [comment]
Yes

**Comment by lingqingmeng** [comment]
Should have a wait timer? AFAIK it tries two times (if, else if ....) and
if that doesn't work it craps out.

**Comment by Quillwerth** [comment]
We could pull "back-up" stages at the same time that we request the
scenario from the server. Furthermore, we could just have them play the
same stage over and again, based on the assumption that we actually do know
how good they are.

In any case, a crash is the wrong path. Notifying the player of disruption
and having them fix it, without the game going down, is the proper
behaviour.
Should have a wait timer? AFAIK it tries two times (if, else if ....) and
if that doesn't work it craps out.

On Thu, Apr 3, 2014 at 11:25 PM, AOEChamp notifications@github.com wrote:

> Yes
> 
> ## 
> 
> Reply to this email directly or view it on GitHub<
> https://github.com/4950/DirtyGame/issues/305#issuecomment-39530799>
> .

## 

Reply to this email directly or view it on
GitHubhttps://github.com/4950/DirtyGame/issues/305#issuecomment-39577177
.

**Comment by AOEChamp** [comment]
Networking should be more robust now. Lets the user know what's going on, and an error message if it fails to send. We can change number of attempts and time between attempts as needed.

If anyone wants to test, use Clumsy to simulate lag or dropped connections.
http://jagt.github.io/clumsy/download.html
