### ISSUE TITLE
Server should send scenario to the clients

### ISSUE THREAD

**Issue by FourierTransformer** [4950/DirtyGame#314]
We don't want the clients to have a list of scenarios to choose from (locally on their computer). The idea is to have a list of scenarios on the server (that we can easily add to) that will then be sent down to the client to be played.

**Comment by JaredPoetter** [comment]
Step by step process that we want to happen:
Client starts the game and clicks on the arena map.
Client's game talks to the server to get a scenario that is the closest to their current ELO score.
Server sends the full scenario information, i.e. location and number of each of the monsters.
Client's game will translate the data sent from the server for the scenario.
The scenario is played.
Once the scenario is completed the data is sent back to the server.
The ELO and Linear ELO for the player and scenario are updated.

**Comment by Quillwerth** [comment]
We want this done by Monday. @AOEChamp

**Comment by AOEChamp** [comment]
Completed. 

Server will send down complete scenario XML for each round, based on current ELO.

If a scenario is not returned for whatever reason(server error, bad network), the game will pick one of the local scenarios in Scenarios.xml.

**Comment by JaredPoetter** [comment]
Is the scenario then parsed to create the scenario on the client side? I am assuming but I want to make sure.

**Comment by AOEChamp** [comment]
It's not saved locally if that's what you're asking

**Comment by JaredPoetter** [comment]
No I am saying that once the server passes a scenario to the client in the XML format does the client then parse it out and create the scenario. Or does this still have to be done.

**Comment by AOEChamp** [comment]
The scenario xml is sent from the server and parsed each round
