### ISSUE TITLE
Linear ELO doesn't currently work

### ISSUE THREAD

**Issue by FourierTransformer** [4950/DirtyGame#316]
We were going to take a look at this tonight, but none of us have access (see #315). Linear ELO doesn't appear to be updated correctly atm. Not quite sure what's up with that, and now we aren't able to debug it...

**Comment by AOEChamp** [comment]
Problem was because because completed flag wasn't being set upon round end. Also, LinearELO for the first scenario is super low for some reason. So ELO gains for that scenario round to 0. Probs not a problem once we reset ELO. But do we want ELO clamping(so that there is a minimum gain for wins?)

**Comment by Quillwerth** [comment]
I don't believe so. If the math says you should stomp, then you shouldn't be recognized for it.

Is this a closed issue?

**Comment by AOEChamp** [comment]
It is now
