### ISSUE TITLE
Queue events instead of triggering events

### ISSUE THREAD

**Issue by sturmE** [4950/DirtyGame#32]
I think it would be better to queue events over the course of a frame, then act on those events at the beginning of the next frame. If we act upon events immediately, this could cause chaining of events one after another.

Any thoughts? @Duffman9205

**Comment by baylorw** [comment]
Your standard game loop is

while (1)
  getInput()
  update()
  render()

All events should be handled in update(). If you're suggesting putting all events in Queue<Event>, how does this relate to frame rate? Are you proposing that we set a between-frame counter and then process all the events until the queue is empty or time expires?

Chained events are not a bad thing so long as they're written intelligently and not looped. That's normally the responsibility of the designer, not the engine. However, one issue we haven't talked about is delayed events or delayed event handling, which is part of scheduling. i'll add a separate ticket for that.

**Comment by Duffman9205** [comment]
Yes, the idea was to have a time limit for processing events to maintain frame rate and then we'd also know when events are being processed (also they wouldn't interrupt the process currently going on).

The idea of queuing events was from Game Coding Complete (4th ed.)

**Comment by sturmE** [comment]
The reasoning for my suggestion is that I dont trust anyone. I can already see events triggering events triggering events...and so on. As you said, we could just let it happen and blame the designer. I feel like if we queue events instead of triggering, it will be more obvious when this happens.

**Comment by mplewis** [comment]
Not trusting anyone is also a good argument for throwing loud game-breaking
exceptions when things like animations break instead of debugging silently.

**Comment by sturmE** [comment]
Its going to break either way, just how you want it to break.

**Comment by mplewis** [comment]
Break loud and often. If it breaks it should be fixed.
