### ISSUE TITLE
Scenario ELO table needs to be updated

### ISSUE THREAD

**Issue by FourierTransformer** [4950/DirtyGame#322]
The ELO table doesn't have any of the new scenarios from the 28 new scenarios.

**Comment by FourierTransformer** [comment]
Ideally this will be automatics?

**Comment by AOEChamp** [comment]
It is automatic. Just play through them

**Comment by FourierTransformer** [comment]
We totally did. It didn't actually update the sql

**Comment by FourierTransformer** [comment]
Totally hard coded the new scenarios in the elo table
