### ISSUE TITLE
Player ELO is not being created for new Players

### ISSUE THREAD

**Issue by FourierTransformer** [4950/DirtyGame#323]
We cleared the player elo table to get ready for the internal beta, and now when someone plays the player elo table is not being updated.

@fualkner plans on taking care of this.

**Comment by AOEChamp** [comment]
I'm guessing the INSERT no longer works because the table structure changed. Should be a simple fix in the sql code

**Comment by JaredPoetter** [comment]
It does not work for new players created after the truncation of the table or players created before the truncation of the table. Just wanted to make sure this was stated.
