### ISSUE TITLE
Fix the Linear ELO in the ELO Verifier SpreedSheet

### ISSUE THREAD

**Issue by JaredPoetter** [4950/DirtyGame#324]
Fix the Linear ELO in the ELO Verifier SpreedSheet

**Comment by AOEChamp** [comment]
What is this?

**Comment by JaredPoetter** [comment]
This is a Google SpreedSheet that I made to verify the ELO calculations are correct. We are not able to run unit tests on the SQL code and we were getting tired of going through the math on the board. I finished it last night but I am not sure I was given the correct equation for the Linear ELO at the other meeting.
