### ISSUE TITLE
Fill out scenario XML in SQL table or create a script for automation

### ISSUE THREAD

**Issue by AOEChamp** [4950/DirtyGame#326]
The ScenarioXML column of the ScenarioELOes table needs to be filled out with xml for each scenario. The format is as below:

<?xml version="1.0" encoding="utf-8"?>
<root id="Scenarios">
    <scenario name="Arena_scenario_M1_R0_S0"
        difficultyScore="0.50"
        map="Arena.tmx"
        playerX="652"
        playerY="784">
        <spawner xPosition="1112"
            yPosition="1040"
            monsterType="MeleeMonster"
            monsterWeapon="Monstersword"
            numberOfMonsters="1"
            timeSpanMilliseconds="1000"
            healthUpModifier="0"
            damageUpModifier="0">
        </spawner>
    </scenario>
</root>

**Comment by FourierTransformer** [comment]
Should this actually look like:

```
<?xml version="1.0" encoding="utf-8"?>
      difficultyScore="0.50"
      map="Arena.tmx"
      playerX="652"
      playerY="784">
    <spawner xPosition="1112"
        yPosition="1040"
        monsterType="MeleeMonster"
        monsterWeapon="Monstersword"
        numberOfMonsters="1"
        timeSpanMilliseconds="1000"
        healthUpModifier="0"
        damageUpModifier="0">
    </spawner>
```

Because otherwise multiple spawners will not be a thing. (or even one spawner?)

**Comment by JaredPoetter** [comment]
I guess this is something that we should look at tonight during our meeting.

**Comment by lingqingmeng** [comment]
Is the problem here in the XML generator? It can't generate scenarios with more than 1 monster?

**Comment by FourierTransformer** [comment]
Closed
