### ISSUE TITLE
Go through scenarios in the Scenarios.XML file

### ISSUE THREAD

**Issue by JaredPoetter** [4950/DirtyGame#328]
I am talking about removing the junk scenarios that we created in the beginning of this semester to test out the game and the scenario code.

Do not forget to change the client code that selects the next scenario because last time I looked at it and worked on it it was just using a counter and a modulus to stay within a certain range of scenarios.

**Comment by AOEChamp** [comment]
Already removed these

**Comment by JaredPoetter** [comment]
Great.
