### ISSUE TITLE
Creating the scenarios for all the different monsters

### ISSUE THREAD

**Issue by JaredPoetter** [4950/DirtyGame#330]
The idea is to have a wide range of scenarios that will be easy to hard. Also the scenarios should have 2-3 monster types during each scenario to make the game fresh and enjoyable for the player.

@FourierTransformer and @fualkner were going to work on this.

**Comment by FourierTransformer** [comment]
Hey, this is done. All the new scenarios are in the Database. The map was updated ( #334 ). This is done.
