### ISSUE TITLE
Internal play testing

### ISSUE THREAD

**Issue by JaredPoetter** [4950/DirtyGame#332]
This is dependent on the issues; #330, #331, #306; being completed.

**Comment by bkern24** [comment]
Is this testing we plan on doing before thursday night?

**Comment by JaredPoetter** [comment]
Yes it would be nice to have some of this testing done before Thursday because it is going to be a few hours per person to get the scenarios seated. But this cannot really be done until the other issues are completed. The main one is getting the new scenarios with all the monsters we are wanting and the balanced monster attacks and health. Does that make sense?
