### ISSUE TITLE
FLAME TOWER DOESN'T ROTATE

### ISSUE THREAD

**Issue by FourierTransformer** [4950/DirtyGame#336]
...and it's crunch time!

**Comment by bkern24** [comment]
I can work on this late tonight.... Like 10 pm if no one else has started

**Comment by sturmE** [comment]
Dont trust him.

**Comment by AOEChamp** [comment]
I'll look into it first :P

**Comment by bkern24** [comment]
Alright well I just got home.I'll check back in at 10:30, so if I haven't heard anything I'll assume you finished it
