### ISSUE TITLE
PlayerScore incorrectly(?) calculated for SuicideBombers

### ISSUE THREAD

**Issue by Quillwerth** [4950/DirtyGame#338]
From GameSessionController.cs:

 SET @TotalHealth = @TotalHealth + CASE @Monster 
        WHEN 'MeleeMonster' THEN 240
        WHEN 'SuicideBomber' THEN 1
        WHEN 'LandmineDropper' THEN 120
        WHEN 'RangedMonster' THEN 120
        WHEN 'Grenadier' THEN 100
        WHEN 'Flametower' THEN 100
        WHEN 'SnipMonster' THEN 120
        WHEN 'WallHugger' THEN 25
        ELSE 0
    END;

Note that addition for 'SuicideBomber'. That's not a true reflection of its health, which is 60. Why did we write it like this? @AOEChamp

**Comment by AOEChamp** [comment]
Because magic. Yeah, that needs to be updated when we change health. Idk
how else the sql would know max health for monsters.

**Comment by Quillwerth** [comment]
Fixed it. Fix is sitting in "god", and was pushed to the server.
