### ISSUE TITLE
Melee damage

### ISSUE THREAD

**Issue by sturmE** [4950/DirtyGame#34]
Right now we kill monsters by walking over them. Next, we want to kill monsters by explicitly attacking them.

How are we going to do this from a melee perspective. My thoughts are to just do collision detection for an attack when a "melee" action is happening. So you'd have to walk on top of the monster then attack to kill them.

Thoughts?

**Comment by bkern24** [comment]
Jared and I will take this one. Jared is gonna supply the animation, and then I'll work on the creating an entity and such (Physics) for the melee.

Bazinga

**Comment by AOEChamp** [comment]
This seems to be working well enough for the current milestone
