### ISSUE TITLE
Flame Tower Shield doesn't always diseappear, and can be attacked whenever

### ISSUE THREAD

**Issue by bkern24** [4950/DirtyGame#345]
Killed all enemies tower shield didn't go away. Attacked flame tower before killing all enemies created hard failure.

**Comment by Quillwerth** [comment]
We should just nix the feature. It's unnecessary to the gameplay, and the story is basically an inside joke.

**Comment by JaredPoetter** [comment]
+1 That is exactly what I was thinking Patrick.

**Comment by Quillwerth** [comment]
Game just crashed on me because of this. I thought everything on the map was dead. If there's a general consensus that the should be removed (more trouble than it's worth), then let's do that. @AOEChamp, I'm not sure where in the code this shield exists; could you remove it, or give me a hint?

**Comment by Duffman9205** [comment]
I also just had my game crash when I killed the tower. I think it was the last enemy, but I'm not sure.
![killed tower crash](https://cloud.githubusercontent.com/assets/5514621/2749653/605d14e8-c815-11e3-90d6-67d95d404cda.PNG)

**Comment by Duffman9205** [comment]
Just got the same crash again -- I killed the tower when there was still an archer alive
