### ISSUE TITLE
Really, 15 second server connections?!

### ISSUE THREAD

**Issue by Quillwerth** [4950/DirtyGame#347]
Okay, I can't ignore this glaring UX flaw any more. Playing the game is actually PAINFUL because of it. We log a ton of GameEvents, probably because we used to give a damn what tactics people were using. I don't think we care anymore: we care about players, and just raw plays of levels.

Three things I want to know:
1. What times are the rest of you getting after levels, on average?
2. What events do we _actually_ still use? I've heard MonsterKilled is important. What about hits?
3. Do we send all the events on round end? Can we send events live during gameplay instead?
4. Other ideas for the speed problems? Can we just increase our hardware?

**Comment by bkern24** [comment]
Increase hardware!

**Comment by Quillwerth** [comment]
Will that bill the university more?

Do I care?

**Comment by Quillwerth** [comment]
@bkern24 , could you answer the first question? If it's just my internet, then so be it.

Just had a "retrying connection" timeout, twice, despite having internet the whole time. Has anyone else seen that?

**Comment by bkern24** [comment]
I hope so.....

**Comment by bkern24** [comment]
No its really slow too. You can tell because one melee = fast and 10 wall
huggers = shoot me

**Comment by Quillwerth** [comment]
Tonight (hopefully) I'll do a total sweep of the code, looking for every mention of certain event types. Anything that's not being read in by code currently (i. e. is just being logged to the server for "research") will be nixed. @AOEChamp could probably greatly increase my speed here, if he can tell me which events are mission critical.

**Comment by AOEChamp** [comment]
I don't know off-hand. Check the SQL code. Any events not being used in SQL
are probably not critical.

**Comment by AOEChamp** [comment]
The other thing to do is use Fiddler or another sniffer to see exactly what is being sent, how large it is, etc. We can also set it up so that data gets sent asynchronously every few seconds. I initially attempted that but was getting some errors. Might be do-able though.

**Comment by AOEChamp** [comment]
Furthermore, it seems that azure website policy has an idle timeout period. After the idle period(20 min default, I believe), the site shuts down. The next request will take an extra 10-15s as the site boots up. The policy is not modifiable, so the only solution(if this is actually a problem) is to switch from a website to a Virtual Machine

**Comment by AOEChamp** [comment]
Hey @fualkner try out the code in my branch. It sends current data async every 5 sec. Should improve end game performance significantly. Let me know if it reduces send time at the end.

**Comment by Quillwerth** [comment]
This is the best thing ever. I'm not exaggerating when I say 300% faster. I might be under the actual speed increase. Nice, nice, nice work. Once this gets merged, we'll close.
