### ISSUE TITLE
Text gets cutoff in Options menu

### ISSUE THREAD

**Issue by Duffman9205** [4950/DirtyGame#348]
The new font makes the Capture Mouse text in the Options menu show up as "pture Mou"

**Comment by Duffman9205** [comment]
Text also gets cutoff in the pop-up message when it can't contact the server.

**Comment by Quillwerth** [comment]
Text gets cut off a lot of places. How can we _solve_ this? Increased box sizes, I'm guessing... hopefully we can find those.

**Comment by AOEChamp** [comment]
Increase label sizes or revert to the old font. In the future, you should
add a new font and change only the elements you need to change. The default
font is supposed to be a "safe" font.
