### ISSUE TITLE
Ranged Damage

### ISSUE THREAD

**Issue by sturmE** [4950/DirtyGame#35]
Right now we kill monsters by walking over them. Next, we want to kill monsters by explicitly attacking them.

How are we going to do this from a ranged perspective. For a initial implementation we can just shoot an arrow that flies for x amount of time or x amount of distance then disappears. We could just do collision detection with this arrow and monsters.

Thoughts?

**Comment by rthonglyvong** [comment]
Maybe point target, after x time, depending on distance, a collideable
object generates and does damage

**Comment by sturmE** [comment]
Point targeting with the mouse would be a good thing to have. To start, I think we can just shoot a projectile straight in the direction we are facing.

**Comment by AOEChamp** [comment]
Basic ranged attacks are done, so I think I'll close this. Use right mouse to fire. Shoots where mouse is pointed...
