### ISSUE TITLE
Game Crash on Killing Tower

### ISSUE THREAD

**Issue by dawl** [4950/DirtyGame#350]
This has happened 3 times so far (~140 rounds), but when I killed the tower (there were other monsters left) I got this error
![error1](https://cloud.githubusercontent.com/assets/3344817/2749827/c44a67f4-c828-11e3-9cd7-2a6e39f2b7bd.png)

**Comment by dawl** [comment]
Call it repeatable.  Just had it happen again, killed the tower with one archer left and got the same error.

**Comment by JaredPoetter** [comment]
I can second this. If you leave one ranged and then kill the tower it will crash the game. At least it is a repeatable bug. I will try to see if this happens with any other enemy types with the flametower.

**Comment by JaredPoetter** [comment]
It is repeatable with a melee too.
