### ISSUE TITLE
I CAN'T CONNECT TO THE SERVER

### ISSUE THREAD

**Issue by FourierTransformer** [4950/DirtyGame#352]
but Paul totally can. WHAT THE WHAT?!

**Comment by AOEChamp** [comment]
teh suk

**Comment by AOEChamp** [comment]
need more info

**Comment by FourierTransformer** [comment]
It times out every time and I play the same level for days. I'm connected
to the same internet as Paul.

Not sure if it's a one off connection problem. Will try again later

**Comment by dawl** [comment]
Happened to me multiple times, seemed to happen on levels where it takes me a long time to kill all the enemies.  Usually levels with a lot of Grenadiers where it takes me several minutes to kill them.

**Comment by lingqingmeng** [comment]
Has this been fixed with the async changes?

**Comment by dawl** [comment]
Yes
