### ISSUE TITLE
Switching to Linear ELO when we go to public release

### ISSUE THREAD

**Issue by JaredPoetter** [4950/DirtyGame#355]
Switching to Linear ELO when we go to public release. This is the ELO that the game is going to use to pick a scenario for the player.

**Comment by JaredPoetter** [comment]
Your async branch has been tested by a couple of us and it looks solid. So you can put those changes in and this change to the server.

**Comment by Quillwerth** [comment]
Async is client-side, and has already been merged to develop by me.

**Comment by JaredPoetter** [comment]
Ok so now we just need to get these two server changes done for tomorrow morning. The background image is just a cosmetic change that is not required at all.
