### ISSUE TITLE
Testing of ASYNC netoworking and Patrick's changes

### ISSUE THREAD

**Issue by JaredPoetter** [4950/DirtyGame#360]
@dawl @coala2000

**Comment by JaredPoetter** [comment]
@Duffman9205 @bkern24 Can you also check this branch/do more play testing? https://github.com/4950/DirtyGame/tree/severinSavesTheDay

Thanks

**Comment by JaredPoetter** [comment]
Let us know if you have any crashes or bugs with the branch.

**Comment by bkern24** [comment]
I can tomorrow, is that soon enough? What specifically am I looking for?

**Comment by JaredPoetter** [comment]
Well we are wanting to make sure the async of sending the scenario information during the round is not causing lag or other problems. We are going to publish the game to Baylor's classes on Wednesday.

If you are not able to look at it until tomorrow just try to get more play testing done because only about 2 or 3 of us were able to get through all of the scenarios. I think you were one of them.

**Comment by bkern24** [comment]
Well technically I made it through 150 ish rounds but I got reset :(. So did we change how the server interacts during the game? Before the game sent all information after the game round has ended, asynchronous makes it seem otherwise?

**Comment by JaredPoetter** [comment]
It will send data every 5 secs to the server instead of all at once at the end of the scenario.

**Comment by JaredPoetter** [comment]
You are still going to be going through all 75 scenarios in the same order. The code that is going to pick the closest scenario ELO Linear is going to be put in tomorrow night.

**Comment by JaredPoetter** [comment]
Also I just played through 50 scenarios and it seems to work fine no crashes. It is a little laggy with all archers and wall huggers because of all the objects on the screen but it is still playable.

**Comment by bkern24** [comment]
Okay cool I'll let you guys know. Especially since I have to use my small and slow computer... I.e. if I don't see a difference on that then it should be fine.

**Comment by dawl** [comment]
Just ran 50 rounds on Patrick's branch.  Never had any connection errors.  Async seems to have fixed the problem.

**Comment by JaredPoetter** [comment]
It seems like it can be made into a pull request. @fualkner

Also @AOEChamp you can probably change back the server to push out the scenarios based on linear elo once Patricks and your changes are into develop.

**Comment by Quillwerth** [comment]
Already merged to develop.
