### ISSUE TITLE
Publish new EXE for mass play testing.

### ISSUE THREAD

**Issue by JaredPoetter** [4950/DirtyGame#368]
We need to publish the new EXE to the server because right now it does not have the ASYNC code in it.

**Comment by Quillwerth** [comment]
This is something I don't know how to do. Also, this depends on #364.

**Comment by JaredPoetter** [comment]
@AOEChamp Looks like we are getting close to being ready for publishing the final version for the mass play testing. We can wait for the other things like the fix to the installer and other minor things like the background image which is not a required thing for mass data collection.

**Comment by AOEChamp** [comment]
I will publish sometime tonight once all the important changes are in

**Comment by Quillwerth** [comment]
Wow, we really think the fix to the installer is minor? After tomorrow,
it's not even important. Nor the background image. Or anything.
