### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by sturmE** [4950/DirtyGame#37]
Console.Writeln() shits on everything when used in systems. We need to implement a logger that buffers log strings then writes them once per frame. 

Also, everyone needs to use it.

**Comment by mplewis** [comment]
I can take a look at this.

**Comment by baylorw** [comment]
Normal logging (to disk) is done with tools like log4net. i assume we want an online one. That means we need a large read-only text GUI object that can be shown/hid with a hotkey.

**Comment by sturmE** [comment]
That actually does bring up a good point. It would be good to have log levels (ex. Debug, Error) but even further (Combat, Animation). This way if we want to display a combat log, we can easily pick out the correct log statements to display in the log.
