### ISSUE TITLE
What happened to dawl?

### ISSUE THREAD

**Issue by FourierTransformer** [4950/DirtyGame#371]
So, @fualkner and I noticed that dawl has dissipated. We checked the sql, and was totes not there. So, did someone delete dawl? Did dawl die? Do we even KNOW?! #MurderMystery2014

**Comment by Quillwerth** [comment]
He was there the whole time. Whoops.

**Comment by AOEChamp** [comment]
Not on the boards. Maybe he needs to play a game.

**Comment by dawl** [comment]
I just needed to play some, in 7th now
