### ISSUE TITLE
Broadcasters 

### ISSUE THREAD

**Issue by baylorw** [4950/DirtyGame#39]
Many engines have a base collision system. This is the basis for other systems such as triggers, broadcasters and location markers.

A broadcaster has a large range and an attenuated signal. If you are at the center, signal strength = 1, if you are at the edge, signal strength might = 0.1.

Broadcasters are used to say "hey notice me". Examples include dead bodies, open doors, room lights and absences. Example: A museum guard walks a patrol after the building has closed. Stationary guards are at the four corners of the building. A giant ruby is in the center. A door is open 50' down the hall. At 50', the guard has a 10% chance of noticing. At 25', the guard has a 50% chance of noticing. Likewise, if the guard walks by the stationary guard position and the guard is missing, the guard doesn't notice from a distance but will probably notice if they're at the position and remembers that someone used to there and has no reason to believe they moved.

Other examples include TVs and refrigerators in The Sims (where it interacts with the agent's desires) and possibly calculating aggro/intent to engage (although this is the sum of agents in a given direction and is normally done with an influence map).

i don't know if this game has a use for that but the designers should consider it.

Possible uses: An electric user noticing there's water nearby, a sniper noticing a good sniping location, a parkourist noticing a wall he can scale, the agent's main rival being nearby.

**Comment by bkern24** [comment]
Implemented The Physics.Query function, so somebody could use this func and then fire an event etc.

**Comment by AOEChamp** [comment]
Not needed for now
