### ISSUE TITLE
Location Markers

### ISSUE THREAD

**Issue by baylorw** [4950/DirtyGame#42]
We might want to add location markers. A location marker is a node that has a name or tag.

Example 1: Agent walks into a room. Trigger at door says to walk over to light switch and flip on the light. The light switch has a node next to it marked CafeteriaLightSwitch2 and the trigger script is "invoker.walkTo("CafeteriaLightSwitch2")". 

Example 2: Agent's state = Patrolling. Receives event onTakeDamage(). State switches to Fighting. In the fighting state, guard uses cover. Searches for all nodes within 10' where tag="cover". Finds closest node and moves to it.

**Comment by AOEChamp** [comment]
Pretty sure this isn't needed anymore
