### ISSUE TITLE
Add health system

### ISSUE THREAD

**Issue by mplewis** [4950/DirtyGame#43]
- Entities start with an integer amount of health
- Attacks do damage
- When an entity reaches 0 health, it dies

**Comment by sturmE** [comment]
Label your shit

**Comment by mplewis** [comment]
NO

**Comment by sturmE** [comment]
I think a good start to this would be to have a health system that essentially is "everyone has 0 health." Then if we get that working obviously expand.

**Comment by bkern24** [comment]
I have some good ideas to at least get things started with the health system. i.e start with Eugene's suggestion

**Comment by AOEChamp** [comment]
I kinda realized I needed a health system while I was working on ranged attacks, so I just made one. Didn't see Brandon's branch until later. The systems are really similar, so they can be easily merged.
