### ISSUE TITLE
Build UDP networking demo

### ISSUE THREAD

**Issue by mplewis** [4950/DirtyGame#44]
Demonstrate a basic implementation of a UDP client/server in C#.

Build a chat server that does the following:
- Accepts client connections
- Broadcasts all received UDP messages to all connected clients

**Comment by Quillwerth** [comment]
Closed. Removing all evidence of Matt from this project. JK, we need to have a design conversation about the shape of the server. #120

**Comment by mplewis** [comment]
I'LL... BE... BACK

I'm totally willing to have coffee chats about server arch though! hmu
