### ISSUE TITLE
Aggro Radius

### ISSUE THREAD

**Issue by sturmE** [4950/DirtyGame#46]
Make monsters run at player when they detect the player coming within a specified radius. https://github.com/4950/ShittyPrototype/issues/39

**Comment by Quillwerth** [comment]
This is a matter of changing ~2 lines of code in AIManager. #45 will be roped into this almost by accident.

**Comment by dawl** [comment]
It was a little more than 2 lines of code, but monsters now monsters run towards the player, not each other.

**Comment by dawl** [comment]
Check it out on origin/etzel/AIImprovements
