### ISSUE TITLE
Scheduling

### ISSUE THREAD

**Issue by baylorw** [4950/DirtyGame#49]
In many game engines you have the ability to say "trigger this event/call this method in X ms". 

This is used for many things. One is procedural animation - every 10ms strobe a color or grow an item or count down a GUI effect timer, etc. The alternative to this is to use an unbound clock/fast as you can render approach and base continuous processes on a delta approach (i.e., float changeInTime = now - lastTime; changeInAlpha = fadeRate \* changeInTime). Some people find the scheduling approach to be more efficient.

Another use is for when you legitimately want something to wait a bit. For example, if a guard sees a body, he should wait a second or two to respond to have human-like reaction time. Igniting gas should take a few seconds to spread across the full pool. Running as fast as possible would result in instant ignition and super human reflexes.

Eugey has another issue open for a queue scheduler. This might be a reason to adopt that, although it would not be a queue but something a little different.

**Comment by AOEChamp** [comment]
Not needed as of now
