### ISSUE TITLE
Mounting

### ISSUE THREAD

**Issue by baylorw** [4950/DirtyGame#50]
Some 2D and most 3D game engines have the concept of mounting. A weapon mounts to a hand, a hat mounts to a head, etc. This requires a sprite to have 0..n mount points and a way of specifying gun mount point 7 mounts at 90 degrees to mount point 13 on the sprite.

In addition to graphical flourish, mount points are used to attach sound sources, illumination sources and things the environment and agents respond to. For example, when the great forest spirit walks, all grass within 5m of him dies. Rather than put that in the monster class, you'd have a non-visual effect object mounted to the forest spirit. Other things you can attach are things like blood (so that allies notice you're bleeding) or aggro (in HL2, you can splash an enemy with a scent that makes nearby antlions chase them).

i don't know if we need this but it's worth considering.

**Comment by sturmE** [comment]
I like the idea of this for weapons. It is definitely something we could do if we have time to do.

**Comment by AOEChamp** [comment]
Not part of game specs anymore
