### ISSUE TITLE
InputSystem

### ISSUE THREAD

**Issue by JaredPoetter** [4950/DirtyGame#51]
An InputSystem that looks at the keyboard state and passing the information to entities that want the keyboard input. So maybe a inputComponent that tells the program that that entity wants that information.

**Comment by sturmE** [comment]
I'll take this one.

This is how I plan on implementing it.

I am going to abstract button presses into Actions and State. An action is defined as when you just care about the button being pressed and thats it.(ex. I want to cast a spell so I press 'A'). A state is when you care about something being help down (ex. Keep moving player left until button is released)

So, if you want to get a callback when a button is pressed you have to register this with the inputmanager. if you register as wanting an "action", you will get ONE callback everytime the button is pressed down. If you register as wanting an state, you will get a callback everytime the state of the key changes.

**Comment by sturmE** [comment]
I have a good working version on input in my branch  

564798e206a7cdc7d0f2a7bbb69e5b866d93afa5

I am still working on integrating into ECS, but you can still use it. See the simple example for the baseContext in Dirty.cs

**Comment by sturmE** [comment]
Actually, I'll throw integrating it into a new ticket and make a pull request.
