### ISSUE TITLE
Finite Automata AI System

### ISSUE THREAD

**Issue by Quillwerth** [4950/DirtyGame#52]
Build an extensible AIComponent and AISystem that uses FA to model behaviour.
- States (vertices) contain a "Directive" which can ask the MovementSystem/CombatSystem for certain things ("Hey, I want to move in this direction at top speed", "Hey, I want to use a ranged attack").
- Transitions (edges) contain a "Condition" which must be satisfied to traverse the edge. If no edge is traversed, we stay in the same place.

AIComponent will have the graph, AISystem will control movement and directive-passing.

```
&& break; //PBS
```

**Comment by baylorw** [comment]
i have a lecture on FSMs and related items for games if you want them. However, those are falling out of vogue. The new thing is a variation on heirarchical FSMs / pushdown automata called Behavior Trees. i might even have one in C# kicking around.

**Comment by Quillwerth** [comment]
I'll take whatever you can send me. Implementation is a bit of a nightmare... Doable, but irritating.

**Comment by Quillwerth** [comment]
Closed. Way outdated, and designed with swappable AI in mind. This isn't our plan anymore.

**Comment by AOEChamp** [comment]
FSMs are for babies. I vote Behavior Trees
