### ISSUE TITLE
Implement chromakey in the spritesheets

### ISSUE THREAD

**Issue by JaredPoetter** [4950/DirtyGame#56]
Make it so that the sprite sheets can have a solid color background and it can be removed by the program.

**Comment by baylorw** [comment]
Why would we want this?

Does XNA not support this? The tools i'm used to do but you have to tell it which color to use, which is a bitch when you have 2 million colors and no GUI to select the one you need.

If this is important we might be able to write a gimp script for it

**Comment by JaredPoetter** [comment]
I will have to look into it. I did not know if it was something that is already implemented in the XNA library or not. Even if it is something that is implemented in XNA already, I still have to figure out how to use it. So I guess that is what I am really saying with this GitHub issue.

Thanks for letting me know about XNA already having something.

**Comment by mplewis** [comment]
Do transparent PNGs not work? I ask out of ignorance.

**Comment by AOEChamp** [comment]
http://stackoverflow.com/questions/5496677/how-do-i-color-key-in-c-in-xna
answers the question on how to use chroma key in xna. I don't see the need though, when transparency works just fine.

**Comment by AOEChamp** [comment]
You can also replace color after creating the texture, but that's slow. Oh, and you can use a shader to replace the color on the fly.

**Comment by AOEChamp** [comment]
Don't think we need this
