### ISSUE TITLE
Adding two of the same type of components to an entity

### ISSUE THREAD

**Issue by JaredPoetter** [4950/DirtyGame#58]
Eugene your EntityManager code breaks when you try to add another component of a type that is already in that Entity. 

Here is a code snippet that will break the code. Copy this in place of your public Entity CreatePlayerEntity(SpriteSheet spriteSheet) in EntityFactory:

```
public Entity CreatePlayerEntity(SpriteSheet spriteSheet)
        {
            Entity e = entityMgr.CreateEntity();
            Spatial spatial = new Spatial();
            spatial.MoveTo(0, 0);

            Sprite sprite = new Sprite();
            sprite.RenderLayer = RenderLayer.BACKGROUND;

            //Direction Component
            DirectionComponent direction = new DirectionComponent();
            direction.Heading = "Down";      


            sprite.SpriteSheet = spriteSheet;// new SpriteSheet(resourceMgr.GetResource<Texture2D>("playerSheet"), "Content\\PlayerAnimation.xml");
            sprite.SrcRect = new Rectangle(0, 0, 100, 100);

            //Creating an Animation component
            AnimationComponent animation = new AnimationComponent();
            //Changing the animation with the string property
            animation.CurrentAnimation = "Idle" + direction.Heading;

            //Creating an Animation component
            AnimationComponent animation2 = new AnimationComponent();
            //Changing the animation with the string property
            animation2.CurrentAnimation = "Walk" + direction.Heading;

            e.AddComponent(spatial);
            e.AddComponent(sprite);
            e.AddComponent(new Collidable());
            Player controllable = new Player();
            e.AddComponent(controllable);
            e.AddComponent(animation);

            e.AddComponent(animation2);

            e.AddComponent(direction);
            return e;
        }
```

Also I changed Animation -> AnimationComponent so you will need to change this back to try this code in your copy.

**Comment by sturmE** [comment]
about to upload the fix.

On Thu, Nov 7, 2013 at 9:31 PM, Jared Poetter notifications@github.comwrote:

> Eugene your EntityManager code breaks when you try to add another
> component of a type that is already in that Entity.
> 
> Here is a code snippet that will break the code. Copy this in place of
> your public Entity CreatePlayerEntity(SpriteSheet spriteSheet) in
> EntityFactory:
> 
> public Entity CreatePlayerEntity(SpriteSheet spriteSheet)
>         {
>             Entity e = entityMgr.CreateEntity();
>             Spatial spatial = new Spatial();
>             spatial.MoveTo(0, 0);
> 
> ```
>         Sprite sprite = new Sprite();
>         sprite.RenderLayer = RenderLayer.BACKGROUND;
> 
>         //Direction Component
>         DirectionComponent direction = new DirectionComponent();
>         direction.Heading = "Down";
> 
> 
>         sprite.SpriteSheet = spriteSheet;// new SpriteSheet(resourceMgr.GetResource<Texture2D>("playerSheet"), "Content\\PlayerAnimation.xml");
>         sprite.SrcRect = new Rectangle(0, 0, 100, 100);
> 
>         //Creating an Animation component
>         AnimationComponent animation = new AnimationComponent();
>         //Changing the animation with the string property
>         animation.CurrentAnimation = "Idle" + direction.Heading;
> 
>         //Creating an Animation component
>         AnimationComponent animation2 = new AnimationComponent();
>         //Changing the animation with the string property
>         animation2.CurrentAnimation = "Walk" + direction.Heading;
> 
>         e.AddComponent(spatial);
>         e.AddComponent(sprite);
>         e.AddComponent(new Collidable());
>         Player controllable = new Player();
>         e.AddComponent(controllable);
>         e.AddComponent(animation);
> 
>         e.AddComponent(animation2);
> 
>         e.AddComponent(direction);
>         return e;
>     }
> ```
> 
> Also I changed Animation -> AnimationComponent so you will need to change
> this back to try this code in your copy.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/4950/ShittyPrototype/issues/58
> .

## 

Eugene Sturm

**Comment by sturmE** [comment]
fixed
