### ISSUE TITLE
BorderComponent

### ISSUE THREAD

**Issue by bkern24** [4950/DirtyGame#61]
A BorderComponent to store the information of the map boundaries. This way Farseer can create borders to allow for the collision detection of walls and such. This would probably be a new entity, and not a component of the monster/player.

**Comment by bkern24** [comment]
I can do this to ensure that the monsters and players cant run off the map, it will just be a basic height width invisible border for now. Just want the structure to be there

**Comment by sturmE** [comment]
You finished this, close your shit.
