### ISSUE TITLE
New map rendering doesnt work

### ISSUE THREAD

**Issue by sturmE** [4950/DirtyGame#64]
when creating the effect for the new map rendering technique, we need to use the camera transformations.

**Comment by AOEChamp** [comment]
The cam transform won't work, it's on different axis'. I think the two
things that need to be done, is the projection matrix needs to be set so
that we can calculate the number if tiles displayed. Then, we can transform
the 3d cam by a scalar of the 2d cam

**Comment by sturmE** [comment]
I switched the camera to a 3d camera that uses a orthographic projection.

Why does the map need to be on a different axis. If we have the camera looking down on the xy plane and the map is on the xy plane we just need to apply the camera transformation to the map to get it in the correct spot to view. Did i miss something?

**Comment by AOEChamp** [comment]
If the cam is now 3d, then we shouldn't have a problem. Just have to move
the tiles, so that they lie across the right plane. I think they are on the
xy plane at the moment. Not sure what plane our original cam is on, probs
yz or something

**Comment by dawl** [comment]
@AOEChamp Is this issue finished? If so are we good to close it?

**Comment by AOEChamp** [comment]
Done, only took 5hrs
