### ISSUE TITLE
Game Lifecycle

### ISSUE THREAD

**Issue by sturmE** [4950/DirtyGame#76]
According to our game doc, we need to cycle between the combat phase, buy phase and boss phase. We need to setup these game states are what happens in them.

Combat Phase -> monsters are aggressive; player kills shit (this is a time dependent state, lasting 30 seconds)
Buy Phase -> Monsters are passive; player cant move; "Buy" GUI shows up (this is time dependent state lasting 10 seconds)
Boss Phase -> Bigger monster (not time dependent)
Loop

**Comment by AOEChamp** [comment]
I'll start on this one.

**Comment by Duffman9205** [comment]
Have you actually started? If not, I have the basic structure done and would like people to help refine it.

Also, if you have started, please assign the issue to yourself.

**Comment by AOEChamp** [comment]
No, I haven't yet.

**Comment by Quillwerth** [comment]
Closed. This is changing. See: #96
