### ISSUE TITLE
Implement TimeSystem to work with TimeComponent

### ISSUE THREAD

**Issue by JaredPoetter** [4950/DirtyGame#8]
When I was reading through the Conrad's Monster Spawner pull request I noticed that he had a TimeComponent implemented. I think that we should create a TimeSystem that will process all of the entities that have a TimeComponent and increase the time since the last frame was rendered. There are enough of us that need the time since the last render that this could be worth the investment.

Another option I guess is a global variable that we all can access that tells us the time since the last render.

If any of you have a better idea than this please let the group know because this is a rough sketch that I just put together in a couple of minutes.

**Comment by AOEChamp** [comment]
We should just pass time as a param with each components update function. I
would assume that many components require it

**Comment by JaredPoetter** [comment]
Now that I look through some of the code I noticed that we do have this implemented in the ECS with the processEntities method already passing in the float dt which will give the same result. So you can just use this parameter if you want to figure out the time since the last render.

So this means that we should not need a TimeComponent at all then. We can discuss at one of the meetings if we need to have a TimeComponent at all because there might be some reason someone has to keep it.

**Comment by sturmE** [comment]
I think it could be done, but, as you noticed, we pass in dt to all the systems for a reason. One possibility that could be useful in many different places would be something like a ScheduledExecutor in the java world (but not on a sepearate thread). What could happen is you schedule a function call to happen in x seconds. Then, every frame your system could give this "function call scheduler" the dt. If the elapsed time exceeds the x seoncds, it will automatically call your function.

**Comment by mplewis** [comment]
Function callbacks?

I really, really like function callbacks.
