### ISSUE TITLE
Enemy Hierarchy discussion 

### ISSUE THREAD

**Issue by Quillwerth** [4950/DirtyGame#88]
We need to discuss the local enemy hierarchy, and determine if this idea is feasible. Related tickets will be created as discussion evolves.

**Comment by lingqingmeng** [comment]
Can you explain what you mean by local enemy hierarchy? How would local enemy hierarchy be different than what it is now (1 melee 1 ranged type of enemy)?

**Comment by Quillwerth** [comment]
It's a separate concept. I won't explain it here (no time) but we'll
discuss it at the next design meeting.

**Comment by AOEChamp** [comment]
Not relevant anymore
