### ISSUE TITLE
Implement new enemy: Sniper

### ISSUE THREAD

**Issue by Quillwerth** [4950/DirtyGame#91]
An enemy which camps until approached, the Sniper has a visible laser that will trace (follow) the player slowly. Think "rubber band": as it gets closer, it slows down. If it locks onto the player, a 1 second delay will follow, after which the player will be shot for 25 health.

Every constant in this ticket should be easily modifiable, so that during play testing these can change if necessary.

**Comment by JaredPoetter** [comment]
I can look into some of these different types of monsters. I will assign myself to the one I am currently working on.

**Comment by bkern24** [comment]
@fualkner and design team. So right now I am designing the sniper to only show the laser when the player is present within the snipers range.

The sniper will run away if the player comes to close.

Is this similar to the concepts you guys were thinking?

**Comment by FourierTransformer** [comment]
This sounds about right. Just wait on @fualkner to fully confirm.

**Comment by Quillwerth** [comment]
I thought the Sniper had a global range. Did we not write that?

And yes, sniper retreats when the player gets close. He also stops aiming /
firing at this time.

And Shak... it's fualkner. Note the vowel order. You won't tag me unless
it's spelled right (or wrong, I suppose)

**Comment by FourierTransformer** [comment]
@fualkner - we definitely didn't specify. Might've been something implied
that we forgot to explicitly state. Sorry about that. But, yeah, global
should be fine. It will likely need some play-testing to determine if it's
too OP or not.

#VowelOrderMatters

**Comment by bkern24** [comment]
Alright, I can always change the range. The only issue with changing the range for testing is also changing the sprite for the laser. Right now the laser just remains the same size. However, I would like to create sprite animation for the laser, but for now it really doesn't matter. (i.e it won't change the gameplay)

**Comment by AOEChamp** [comment]
I'm assuming the laser will start at an angle and slowly rotate to the
player until it locks on?

**Comment by bkern24** [comment]
Thats what my goal is, just for now the laser will always be the same length no matter the distance of the player. I'm hoping to get another 3 hours to work on it tonight, otherwise I will finish it Monday night for sure..... I spent way too much time figuring out Animation, and got no where :(

**Comment by Quillwerth** [comment]
@AOEChamp the laser doesn't "lock on", per say: if the player crosses it
and keeps moving, the laser will have to follow them in the opposite
direction than it was going.

Can't we just place laser sprites end to end to make a laser of arbitrary
length?

**Comment by AOEChamp** [comment]
Could implement a repeat, or stretch it using the scale option

**Comment by bkern24** [comment]
Like I said I wasn't sure how to work with sprites. As far as I was concerned the sprite displayed its actual size....

@AOEChamp  where is a scaling option present?

**Comment by AOEChamp** [comment]
SpriteComponent has a scale property.

**Comment by bkern24** [comment]
Alright well I'll look into it after I finish the actual movement of the laser then. Thanks guys

**Comment by bkern24** [comment]
@fualkner Oh yeah how close is too close by the way? As in when should the sniper run away from the player?

**Comment by Quillwerth** [comment]
Damn, did we not specify that either? Sad... okay, 200 pixels. Make sure
that that number is easily accessible, so we can rebalance the stats easily.

**Comment by bkern24** [comment]
@fualkner @FourierTransformer 
So I have come across an issue with the sniper when he is attacking. If he is attacking (looking for the player) and he gets hit by an enemy or player, the sniper moves but the laser does not. My question is, is it alright if the sniper becomes "Static" (Rather than Dynamic) when he is searching for the player?

This means that the sniper cannot be moved by enemies or player weapons... i.e he just stands there and takes it like a man. I have already coded him being static (It was easy), but would you rather it be a different way?

Aside from this I am working getting the laser to follow the player, but I ran into a small issue that I believe i fixed but wasn't able to test it yet (Just to update where I am at), and then after this I was going to work on the Attacking Animations.

**Comment by FourierTransformer** [comment]
hmm, so a real-life sniper would be laying dow and not able to take
knockback. Yeah, I'm game if you need to keep him static.

**Comment by FourierTransformer** [comment]
Also, I'm sure you're aware, but this guys laser keeps spinning after you kill him (just something that came up at the meeting)

**Comment by bkern24** [comment]
Technically this is done
