### ISSUE TITLE
Implement new enemy: Landmine Dropper

### ISSUE THREAD

**Issue by FourierTransformer** [4950/DirtyGame#93]
Walks around randomly at 1.3x player speed. If encounters player (roughly 500px distance) it will scurry (1.4x player speed) and attempt to get away from player. Every 4-8 seconds, it will drop a land mine. It has a health of 15.

Landmine is a red dot. If player collides with landmine, 25 damage is done. Other enemies cannot collide with landmine. If the landmine is not stepped on after 30 seconds, it disappears. If the round ends with landmines on the field, they are removed (and will not prevent the round from ending).

Every constant in this ticket should be easily modifiable, so that during play testing these can change if necessary.

**Comment by JaredPoetter** [comment]
I can look into some of these different types of monsters. I will assign myself to the one I am currently working on.

**Comment by JaredPoetter** [comment]
@dawl I will assign this to myself if I get done with the XML for the animations of the new spritesheets that Ling found.

**Comment by lingqingmeng** [comment]
Essential requirements completed:

Currently:
Can drop mines
They do damage
AI implemented
New Weapon type "Landmine"
New Monsters.xml files: LandmineDropper and LandmineWeapon

TODO:
Hitbox change to match sprite
General balance tweaking

**Comment by lingqingmeng** [comment]
Just lost code. Another 4 hours

**Comment by lingqingmeng** [comment]
Above commit was for Landmine Dropper, and I buffed Scattershot for testing purposes, feel free to change it back to normal values (1 sec cooldown, 25 damage). Note: The game actually has a lot of monsters now so you might need it :)
