### ISSUE TITLE
Implement new enemy: Suicide Bomber

### ISSUE THREAD

**Issue by FourierTransformer** [4950/DirtyGame#94]
Suicide Bomber goes at same speed as player. Attempts to follow the player, if he gets within 50px the player, there is a .5 sec delay (in which the player could attack, which will interrupt the explosion) and he blows up- 30 damage will be taken (to the player and himself). It has 30 health. The explosion will do damage up to a 150px radius to all other enemies in the area (also doing 30 damage).

Every constant in this ticket should be easily modifiable, so that during play testing these can change if necessary.

**Comment by JaredPoetter** [comment]
I can look into some of these different types of monsters. I will assign myself to the one I am currently working on.

**Comment by FourierTransformer** [comment]
@AOEChamp, why is the way we do AI going to make everything super hacked together? We should probably bring this up at today's meeting?

**Comment by bkern24** [comment]
Its not too bad, i mean if you seperate the monsters by components you can use your own ai method. Just have to make sure you follow along with returning vector2 if you want movement

**Comment by bkern24** [comment]
Or i should say its useable and we dont have time to redo it.

**Comment by JaredPoetter** [comment]
Done
