### ISSUE TITLE
Implement "Fire Trail"

### ISSUE THREAD

**Issue by Quillwerth** [4950/DirtyGame#97]
Fire trail is an area of the ground set of fire (particle system) for a limited amount of time which blocks only player projecticles and does 5 damage ever .5sec while the player stands on it.

Fire Trail does NOT count as an attack, with regards to the HitRate modifier. If the player is hit by a fire-trail, we add one to both the numberOfAttacksLanded and the numberOfAttacksMade. #104

Fire cannot graze. #107

Every constant in this ticket should be easily modifiable, so that during play testing these can change if necessary.

**Comment by JaredPoetter** [comment]
Unless this is the same thing as the firepower attack code this is something that can wait for the other parts to be completed because I think that there is going to be plenty of other things to work on for this week without this.

**Comment by JaredPoetter** [comment]
Not doing
