### ISSUE TITLE
Implement new enemy: Flametower

### ISSUE THREAD

**Issue by FourierTransformer** [4950/DirtyGame#98]
Does not move. Sits still and rotates one revolution every 3 seconds. It has a range of 150px. The fire that it launches is a fire trail (Reference number #97 for fire trail). If an enemy walks through the fire, it gets a fire trail. Players arrows are stopped in the fire that is left behind (enemies arrows are not). It takes no ranged damage. It has 100 health. A player loses 5 health every .5 sec it is in the fire. Enemies lose none.

Every constant in this ticket should be easily modifiable, so that during play testing these can change if necessary.

**Comment by AOEChamp** [comment]
Tower is done, trail is not. Since we have another ticket for trail, closing this

**Comment by Quillwerth** [comment]
So, the tower sits and fires rotationally... but doesn't do damage?

**Comment by AOEChamp** [comment]
Give me a minute to merge, jeez

**Comment by Quillwerth** [comment]
Can't pull from a phone, bro. Just looking for details... which honestly
should be right here.

**Comment by AOEChamp** [comment]
huh

**Comment by JaredPoetter** [comment]
Adeeb please assign yourself so we know what you are working on. I am just wanting to preventing people from working on the same thing and wasting a lot of time.
