### ISSUE TITLE
Implement Enemy Modifiers

### ISSUE THREAD

**Issue by FourierTransformer** [4950/DirtyGame#99]
Modifier is a "powerup" to a base stat that an enemy has. We must be able to apply any of these bonuses to any enemy type.

Ex: DamageUp modifier will make a monster deal +20% damage. A DamageUp can be applied to a melee unit, archer unit, etc.

**Comment by bkern24** [comment]
I'll look into this while I'm working on the grazing, I assume this will to have some standardization among weapons to work. But i will not assign this to me yet until I finish the grazing part so if someone else wants this just comment.

**Comment by JaredPoetter** [comment]
I just had the idea that if we implement the Modifier System correctly we can use it not only as an increase in the amount of damage or speed but also as a decrease in the speed or range of an enemy. This can be used by a special item that the player can use. Or the system can use the modifiers to make the game easier and harder in the scenario creation.

This might have already been talked about but I figured that I should put it right in the issue for reference.

**Comment by FourierTransformer** [comment]
The enemy modifiers was designed to make the game easier/harder during
scenario creation. Patrick and I didn't really want these to be applied to
the player's weapons- as that should remain constant in this weird battle
of determining scenario difficulty and player skill (aka eliminate
variables that we don't know how to factor in).

**Comment by JaredPoetter** [comment]
That is true. I wasn't thinking about that additional variable for the server AI to create or judge the scenario difficulty.

**Comment by JaredPoetter** [comment]
Done
